#!/usr/bin/env node
/**
 * Write artifacts/shots/plate/INDEX.md: every on/off pair the plate shots
 * produced, grouped the way a reviewer reads them (student-facing first),
 * with absolute paths, and the comparison results beside them when
 * compare.mjs has written its JSON (off-vs-base.json, const-empty-vs-base.json).
 *
 *   node tools/e2e/plate/index.mjs [--dir artifacts/shots/plate]
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { REPO, flag, ROUTES, slug, APP_PLATE } from './common.mjs';
import { STATES, PERSONA_PAGES } from './states.mjs';

const args = process.argv.slice(2);
const dir = path.resolve(REPO, String(flag(args, 'dir', path.join('artifacts', 'shots', 'plate'))));
const widths = ['375', '1440'];

const groupOf = new Map(ROUTES.map((r) => [slug(r.url), r.group]));
for (const s of STATES) groupOf.set(s.name, 'state');
const labelOf = new Map(ROUTES.map((r) => [slug(r.url), `${r.label} (${r.url})`]));
for (const s of STATES) labelOf.set(s.name, `${s.name.replace(/^state-/, '')} (${s.url})`);
for (const p of PERSONA_PAGES) labelOf.set(`${p.persona}/${p.name}`, `${p.name} (${p.url})`);

const ORDER = ['checkin', 'member', 'public', 'state', 'staff', 'admin', 'dev'];
const TITLES = {
  checkin: 'Check-in fast path', member: 'Member routes', public: 'Public routes (signed in, so most redirect)', state: 'Interactive states',
  staff: 'Staff routes', admin: 'Admin routes', dev: 'Dev harnesses (/_ds must be identical on and off)',
};

function readCompare(name) {
  const f = path.join(dir, name);
  if (!existsSync(f)) return null;
  const j = JSON.parse(readFileSync(f, 'utf8'));
  return { j, byFile: new Map(j.rows.map((r) => [r.file, r])) };
}
const offVsBase = readCompare('off-vs-base.json');
const constVsBase = readCompare('const-empty-vs-base.json');
const onVsOff = readCompare('on-vs-off.json');

const mark = (cmp, rel) => {
  if (!cmp) return '';
  const r = cmp.byFile.get(rel);
  if (!r) return 'n/a';
  return r.identical ? 'identical' : r.missing ? 'missing' : `${r.pixels ?? r.size} px`;
};

const lines = [];
lines.push('# Plate screenshots: every pair');
lines.push('');
lines.push(`Generated by \`tools/e2e/plate/index.mjs\`. The plate class is \`${APP_PLATE}\` (src/plate.js). ON is the page as src/main.jsx leaves it; OFF is the same page load with the class removed (tools/e2e/plate/common.mjs). Clock pinned at 2026-10-01 4:00 PM America/Los_Angeles; fixture store reseeded per page. docs/SHAPES.md is the reasoning.`);
lines.push('');
for (const c of [['off-vs-base', offVsBase], ['const-empty-vs-base', constVsBase], ['on-vs-off', onVsOff]]) {
  if (c[1]) lines.push(`- **${c[0]}**: ${c[1].j.identical} identical of ${c[1].j.total} (${c[1].j.differ} differ, ${c[1].j.missing} missing): \`${c[1].j.a}\` against \`${c[1].j.b}\``);
}
lines.push('');

const personas = existsSync(path.join(dir, 'on')) ? readdirSync(path.join(dir, 'on')).sort() : [];
const pages = new Map();
for (const persona of personas) {
  for (const w of widths) {
    const d = path.join(dir, 'on', persona, w);
    if (!existsSync(d)) continue;
    for (const f of readdirSync(d)) {
      if (!f.endsWith('.png')) continue;
      const name = f.replace(/\.png$/, '');
      const k = `${persona}/${name}`;
      if (!pages.has(k)) pages.set(k, { persona, name });
    }
  }
}
const isPersonaPage = (p) => !['admin', 'student'].includes(p.persona);
const groupFor = (p) => (isPersonaPage(p) ? 'persona' : groupOf.get(p.name) ?? 'other');
let pairs = 0;
for (const g of ['persona', ...ORDER, 'other']) {
  const list = [...pages.values()].filter((p) => groupFor(p) === g).sort((a, b) => a.name.localeCompare(b.name) || a.persona.localeCompare(b.persona));
  if (!list.length) continue;
  lines.push(`## ${g === 'persona' ? 'Persona-only pages (parent dashboard, pending gate, signed-out landing and login)' : TITLES[g] ?? g}`);
  lines.push('');
  lines.push('| page | persona | width | on | off | off vs base | const-empty vs base |');
  lines.push('| --- | --- | --- | --- | --- | --- | --- |');
  for (const p of list) {
    for (const w of widths) {
      const rel = `${p.persona}/${w}/${p.name}.png`;
      const on = path.join(dir, 'on', rel);
      const off = path.join(dir, 'off', rel);
      if (!existsSync(on)) continue;
      pairs++;
      const label = labelOf.get(isPersonaPage(p) ? `${p.persona}/${p.name}` : p.name) ?? p.name;
      lines.push(`| ${label} | ${p.persona} | ${w} | \`${on}\` | \`${off}\` | ${mark(offVsBase, rel)} | ${mark(constVsBase, rel)} |`);
    }
  }
  lines.push('');
}
lines.splice(4, 0, `${pairs} on/off pairs.`, '');
writeFileSync(path.join(dir, 'INDEX.md'), `${lines.join('\n')}\n`);
console.log(`index: ${pairs} pairs -> ${path.join(dir, 'INDEX.md')}`);
