// GENERATED by tools/e2e/gen-fixture-schema.mjs -- do not edit by hand.
//
// The public schema as every frozen supabase/*.sql file leaves it: per table,
// its columns (type, NOT NULL, default), primary/unique keys (partial ones
// with their predicate), foreign keys (what an embed resolves through), the
// enum-shaped CHECKs, and columns 'authenticated' cannot SELECT (noSelect);
// plus every callable RPC's argument names. Dev-only: nothing in the
// production build imports this file.

export const SCHEMA = {
 "tables": {
  "access_requests": {
   "columns": {
    "id": {
     "type": "uuid",
     "notnull": true,
     "default": {
      "kind": "uuid"
     }
    },
    "email": {
     "type": "text",
     "notnull": true,
     "default": null
    },
    "full_name": {
     "type": "text",
     "notnull": false,
     "default": null
    },
    "requested_role": {
     "type": "text",
     "notnull": false,
     "default": null
    },
    "note": {
     "type": "text",
     "notnull": false,
     "default": null
    },
    "status": {
     "type": "text",
     "notnull": true,
     "default": {
      "kind": "value",
      "value": "pending"
     }
    },
    "reviewed_by": {
     "type": "uuid",
     "notnull": false,
     "default": null
    },
    "reviewed_at": {
     "type": "timestamp with time zone",
     "notnull": false,
     "default": null
    },
    "created_at": {
     "type": "timestamp with time zone",
     "notnull": true,
     "default": {
      "kind": "now"
     }
    }
   },
   "pk": [
    "id"
   ],
   "unique": [
    {
     "name": "access_requests_one_pending",
     "primary": false,
     "columns": [
      "email"
     ],
     "where": {
      "column": "status",
      "op": "eq",
      "value": "pending"
     }
    },
    {
     "name": "access_requests_pkey",
     "primary": true,
     "columns": [
      "id"
     ],
     "where": null
    }
   ],
   "fks": [
    {
     "name": "access_requests_reviewed_by_fkey",
     "columns": [
      "reviewed_by"
     ],
     "table": "profiles",
     "refColumns": [
      "id"
     ],
     "onDelete": "no action"
    }
   ],
   "enums": {
    "requested_role": {
     "constraint": "access_requests_requested_role_check",
     "values": [
      "student",
      "mentor",
      "parent"
     ]
    },
    "status": {
     "constraint": "access_requests_status_check",
     "values": [
      "pending",
      "approved",
      "denied"
     ]
    }
   }
  },
  "allowed_domains": {
   "columns": {
    "domain": {
     "type": "text",
     "notnull": true,
     "default": null
    },
    "added_by": {
     "type": "uuid",
     "notnull": false,
     "default": null
    },
    "created_at": {
     "type": "timestamp with time zone",
     "notnull": true,
     "default": {
      "kind": "now"
     }
    }
   },
   "pk": [
    "domain"
   ],
   "unique": [
    {
     "name": "allowed_domains_pkey",
     "primary": true,
     "columns": [
      "domain"
     ],
     "where": null
    }
   ],
   "fks": [
    {
     "name": "allowed_domains_added_by_fkey",
     "columns": [
      "added_by"
     ],
     "table": "profiles",
     "refColumns": [
      "id"
     ],
     "onDelete": "no action"
    }
   ],
   "enums": {}
  },
  "app_settings": {
   "columns": {
    "key": {
     "type": "text",
     "notnull": true,
     "default": null
    },
    "value": {
     "type": "text",
     "notnull": true,
     "default": null
    },
    "updated_at": {
     "type": "timestamp with time zone",
     "notnull": false,
     "default": {
      "kind": "now"
     }
    }
   },
   "pk": [
    "key"
   ],
   "unique": [
    {
     "name": "app_settings_pkey",
     "primary": true,
     "columns": [
      "key"
     ],
     "where": null
    }
   ],
   "fks": [],
   "enums": {}
  },
  "approved_emails": {
   "columns": {
    "email": {
     "type": "text",
     "notnull": true,
     "default": null
    },
    "granted_role": {
     "type": "text",
     "notnull": true,
     "default": null
    },
    "added_by": {
     "type": "uuid",
     "notnull": false,
     "default": null
    },
    "created_at": {
     "type": "timestamp with time zone",
     "notnull": true,
     "default": {
      "kind": "now"
     }
    }
   },
   "pk": [
    "email"
   ],
   "unique": [
    {
     "name": "approved_emails_pkey",
     "primary": true,
     "columns": [
      "email"
     ],
     "where": null
    }
   ],
   "fks": [
    {
     "name": "approved_emails_added_by_fkey",
     "columns": [
      "added_by"
     ],
     "table": "profiles",
     "refColumns": [
      "id"
     ],
     "onDelete": "no action"
    }
   ],
   "enums": {
    "granted_role": {
     "constraint": "approved_emails_granted_role_check",
     "values": [
      "student",
      "mentor",
      "parent"
     ]
    }
   }
  },
  "attendance_audit": {
   "columns": {
    "id": {
     "type": "uuid",
     "notnull": true,
     "default": {
      "kind": "uuid"
     }
    },
    "event_id": {
     "type": "uuid",
     "notnull": false,
     "default": null
    },
    "member_id": {
     "type": "uuid",
     "notnull": false,
     "default": null
    },
    "actor_id": {
     "type": "uuid",
     "notnull": false,
     "default": null
    },
    "action": {
     "type": "text",
     "notnull": true,
     "default": null
    },
    "reason": {
     "type": "text",
     "notnull": false,
     "default": null
    },
    "old_value": {
     "type": "jsonb",
     "notnull": false,
     "default": null
    },
    "new_value": {
     "type": "jsonb",
     "notnull": false,
     "default": null
    },
    "created_at": {
     "type": "timestamp with time zone",
     "notnull": true,
     "default": {
      "kind": "now"
     }
    }
   },
   "pk": [
    "id"
   ],
   "unique": [
    {
     "name": "attendance_audit_pkey",
     "primary": true,
     "columns": [
      "id"
     ],
     "where": null
    }
   ],
   "fks": [
    {
     "name": "attendance_audit_actor_id_fkey",
     "columns": [
      "actor_id"
     ],
     "table": "profiles",
     "refColumns": [
      "id"
     ],
     "onDelete": "no action"
    },
    {
     "name": "attendance_audit_member_id_fkey",
     "columns": [
      "member_id"
     ],
     "table": "profiles",
     "refColumns": [
      "id"
     ],
     "onDelete": "no action"
    }
   ],
   "enums": {
    "action": {
     "constraint": "attendance_audit_action_check",
     "values": [
      "insert",
      "edit",
      "delete"
     ]
    }
   }
  },
  "attendance_events": {
   "columns": {
    "id": {
     "type": "uuid",
     "notnull": true,
     "default": {
      "kind": "uuid"
     }
    },
    "user_id": {
     "type": "uuid",
     "notnull": false,
     "default": null
    },
    "type": {
     "type": "text",
     "notnull": true,
     "default": null
    },
    "event_time": {
     "type": "timestamp with time zone",
     "notnull": true,
     "default": {
      "kind": "now"
     }
    },
    "method": {
     "type": "text",
     "notnull": false,
     "default": null
    },
    "location": {
     "type": "text",
     "notnull": false,
     "default": null
    },
    "category": {
     "type": "text",
     "notnull": true,
     "default": {
      "kind": "value",
      "value": "build"
     }
    },
    "overridden_by": {
     "type": "uuid",
     "notnull": false,
     "default": null
    },
    "verified": {
     "type": "boolean",
     "notnull": true,
     "default": {
      "kind": "value",
      "value": false
     }
    },
    "job_id": {
     "type": "uuid",
     "notnull": false,
     "default": null
    },
    "manual_entry": {
     "type": "boolean",
     "notnull": true,
     "default": {
      "kind": "value",
      "value": false
     }
    },
    "geo_ok": {
     "type": "boolean",
     "notnull": false,
     "default": null
    }
   },
   "pk": [
    "id"
   ],
   "unique": [
    {
     "name": "attendance_events_pkey",
     "primary": true,
     "columns": [
      "id"
     ],
     "where": null
    }
   ],
   "fks": [
    {
     "name": "attendance_events_job_id_fkey",
     "columns": [
      "job_id"
     ],
     "table": "tasks",
     "refColumns": [
      "id"
     ],
     "onDelete": "set null"
    },
    {
     "name": "attendance_events_overridden_by_fkey",
     "columns": [
      "overridden_by"
     ],
     "table": "profiles",
     "refColumns": [
      "id"
     ],
     "onDelete": "no action"
    },
    {
     "name": "attendance_events_user_fkey",
     "columns": [
      "user_id"
     ],
     "table": "profiles",
     "refColumns": [
      "id"
     ],
     "onDelete": "cascade"
    }
   ],
   "enums": {
    "category": {
     "constraint": "attendance_events_category_check",
     "values": [
      "build",
      "outreach",
      "volunteer",
      "competition"
     ]
    },
    "method": {
     "constraint": "attendance_events_method_check",
     "values": [
      "nfc",
      "manual",
      "kiosk",
      "auto",
      "auto_close",
      "override"
     ]
    },
    "type": {
     "constraint": "attendance_events_type_check",
     "values": [
      "in",
      "out"
     ]
    }
   }
  },
  "cert_requests": {
   "columns": {
    "id": {
     "type": "uuid",
     "notnull": true,
     "default": {
      "kind": "uuid"
     }
    },
    "member_id": {
     "type": "uuid",
     "notnull": true,
     "default": null
    },
    "skill_id": {
     "type": "uuid",
     "notnull": true,
     "default": null
    },
    "note": {
     "type": "text",
     "notnull": false,
     "default": null
    },
    "status": {
     "type": "text",
     "notnull": true,
     "default": {
      "kind": "value",
      "value": "pending"
     }
    },
    "reviewed_by": {
     "type": "uuid",
     "notnull": false,
     "default": null
    },
    "reviewed_at": {
     "type": "timestamp with time zone",
     "notnull": false,
     "default": null
    },
    "created_at": {
     "type": "timestamp with time zone",
     "notnull": true,
     "default": {
      "kind": "now"
     }
    }
   },
   "pk": [
    "id"
   ],
   "unique": [
    {
     "name": "cert_requests_one_pending",
     "primary": false,
     "columns": [
      "member_id",
      "skill_id"
     ],
     "where": {
      "column": "status",
      "op": "eq",
      "value": "pending"
     }
    },
    {
     "name": "cert_requests_pkey",
     "primary": true,
     "columns": [
      "id"
     ],
     "where": null
    }
   ],
   "fks": [
    {
     "name": "cert_requests_member_id_fkey",
     "columns": [
      "member_id"
     ],
     "table": "profiles",
     "refColumns": [
      "id"
     ],
     "onDelete": "cascade"
    },
    {
     "name": "cert_requests_reviewed_by_fkey",
     "columns": [
      "reviewed_by"
     ],
     "table": "profiles",
     "refColumns": [
      "id"
     ],
     "onDelete": "no action"
    },
    {
     "name": "cert_requests_skill_id_fkey",
     "columns": [
      "skill_id"
     ],
     "table": "skills",
     "refColumns": [
      "id"
     ],
     "onDelete": "cascade"
    }
   ],
   "enums": {
    "status": {
     "constraint": "cert_requests_status_check",
     "values": [
      "pending",
      "approved",
      "denied"
     ]
    }
   }
  },
  "disciplines": {
   "columns": {
    "id": {
     "type": "uuid",
     "notnull": true,
     "default": {
      "kind": "uuid"
     }
    },
    "name": {
     "type": "text",
     "notnull": true,
     "default": null
    },
    "category": {
     "type": "text",
     "notnull": true,
     "default": {
      "kind": "value",
      "value": "General"
     }
    },
    "sort_order": {
     "type": "integer",
     "notnull": true,
     "default": {
      "kind": "value",
      "value": 0
     }
    },
    "created_at": {
     "type": "timestamp with time zone",
     "notnull": true,
     "default": {
      "kind": "now"
     }
    }
   },
   "pk": [
    "id"
   ],
   "unique": [
    {
     "name": "disciplines_name_key",
     "primary": false,
     "columns": [
      "name"
     ],
     "where": null
    },
    {
     "name": "disciplines_pkey",
     "primary": true,
     "columns": [
      "id"
     ],
     "where": null
    }
   ],
   "fks": [],
   "enums": {}
  },
  "discord_calendar_log": {
   "columns": {
    "id": {
     "type": "bigint",
     "notnull": true,
     "default": null
    },
    "run_id": {
     "type": "uuid",
     "notnull": true,
     "default": null
    },
    "event_id": {
     "type": "uuid",
     "notnull": false,
     "default": null
    },
    "post_kind": {
     "type": "text",
     "notnull": false,
     "default": null
    },
    "action": {
     "type": "text",
     "notnull": true,
     "default": null
    },
    "report_only": {
     "type": "boolean",
     "notnull": true,
     "default": {
      "kind": "value",
      "value": false
     }
    },
    "detail": {
     "type": "jsonb",
     "notnull": false,
     "default": null
    },
    "created_at": {
     "type": "timestamp with time zone",
     "notnull": true,
     "default": {
      "kind": "now"
     }
    }
   },
   "pk": [
    "id"
   ],
   "unique": [
    {
     "name": "discord_calendar_log_pkey",
     "primary": true,
     "columns": [
      "id"
     ],
     "where": null
    }
   ],
   "fks": [],
   "enums": {}
  },
  "discord_calendar_posts": {
   "columns": {
    "id": {
     "type": "uuid",
     "notnull": true,
     "default": {
      "kind": "uuid"
     }
    },
    "event_id": {
     "type": "uuid",
     "notnull": true,
     "default": null
    },
    "post_kind": {
     "type": "text",
     "notnull": true,
     "default": null
    },
    "channel_id": {
     "type": "text",
     "notnull": true,
     "default": null
    },
    "channel_name": {
     "type": "text",
     "notnull": true,
     "default": null
    },
    "message_id": {
     "type": "text",
     "notnull": false,
     "default": null
    },
    "content_hash": {
     "type": "text",
     "notnull": true,
     "default": null
    },
    "event_snapshot": {
     "type": "jsonb",
     "notnull": true,
     "default": null
    },
    "status": {
     "type": "text",
     "notnull": true,
     "default": {
      "kind": "value",
      "value": "pending"
     }
    },
    "event_starts_at": {
     "type": "timestamp with time zone",
     "notnull": false,
     "default": null
    },
    "event_ends_at": {
     "type": "timestamp with time zone",
     "notnull": false,
     "default": null
    },
    "posted_at": {
     "type": "timestamp with time zone",
     "notnull": true,
     "default": {
      "kind": "now"
     }
    },
    "updated_at": {
     "type": "timestamp with time zone",
     "notnull": true,
     "default": {
      "kind": "now"
     }
    },
    "cancelled_at": {
     "type": "timestamp with time zone",
     "notnull": false,
     "default": null
    }
   },
   "pk": [
    "id"
   ],
   "unique": [
    {
     "name": "discord_calendar_posts_event_id_post_kind_key",
     "primary": false,
     "columns": [
      "event_id",
      "post_kind"
     ],
     "where": null
    },
    {
     "name": "discord_calendar_posts_pkey",
     "primary": true,
     "columns": [
      "id"
     ],
     "where": null
    }
   ],
   "fks": [],
   "enums": {
    "post_kind": {
     "constraint": "discord_calendar_posts_post_kind_check",
     "values": [
      "calendar",
      "reminder_24h",
      "reminder_2h"
     ]
    },
    "status": {
     "constraint": "discord_calendar_posts_status_check",
     "values": [
      "pending",
      "posted",
      "cancelled",
      "superseded",
      "archived"
     ]
    }
   }
  },
  "event_signups": {
   "columns": {
    "event_id": {
     "type": "uuid",
     "notnull": true,
     "default": null
    },
    "member_id": {
     "type": "uuid",
     "notnull": true,
     "default": null
    },
    "response": {
     "type": "text",
     "notnull": true,
     "default": {
      "kind": "value",
      "value": "going"
     }
    },
    "item": {
     "type": "text",
     "notnull": false,
     "default": null
    },
    "created_at": {
     "type": "timestamp with time zone",
     "notnull": true,
     "default": {
      "kind": "now"
     }
    },
    "updated_at": {
     "type": "timestamp with time zone",
     "notnull": true,
     "default": {
      "kind": "now"
     }
    }
   },
   "pk": [
    "event_id",
    "member_id"
   ],
   "unique": [
    {
     "name": "event_signups_pkey",
     "primary": true,
     "columns": [
      "event_id",
      "member_id"
     ],
     "where": null
    }
   ],
   "fks": [
    {
     "name": "event_signups_event_id_fkey",
     "columns": [
      "event_id"
     ],
     "table": "events",
     "refColumns": [
      "id"
     ],
     "onDelete": "cascade"
    },
    {
     "name": "event_signups_member_id_fkey",
     "columns": [
      "member_id"
     ],
     "table": "profiles",
     "refColumns": [
      "id"
     ],
     "onDelete": "cascade"
    }
   ],
   "enums": {
    "response": {
     "constraint": "event_signups_response_check",
     "values": [
      "going",
      "maybe",
      "declined"
     ]
    }
   }
  },
  "events": {
   "columns": {
    "id": {
     "type": "uuid",
     "notnull": true,
     "default": {
      "kind": "uuid"
     }
    },
    "title": {
     "type": "text",
     "notnull": true,
     "default": null
    },
    "kind": {
     "type": "text",
     "notnull": true,
     "default": {
      "kind": "value",
      "value": "build"
     }
    },
    "starts_at": {
     "type": "timestamp with time zone",
     "notnull": true,
     "default": null
    },
    "ends_at": {
     "type": "timestamp with time zone",
     "notnull": true,
     "default": null
    },
    "location": {
     "type": "text",
     "notnull": false,
     "default": null
    },
    "notes": {
     "type": "text",
     "notnull": false,
     "default": null
    },
    "created_by": {
     "type": "uuid",
     "notnull": false,
     "default": null
    },
    "created_at": {
     "type": "timestamp with time zone",
     "notnull": true,
     "default": {
      "kind": "now"
     }
    },
    "updated_at": {
     "type": "timestamp with time zone",
     "notnull": true,
     "default": {
      "kind": "now"
     }
    },
    "rsvp_enabled": {
     "type": "boolean",
     "notnull": true,
     "default": {
      "kind": "value",
      "value": false
     }
    },
    "capacity": {
     "type": "integer",
     "notnull": false,
     "default": null
    },
    "series_id": {
     "type": "uuid",
     "notnull": false,
     "default": null
    },
    "mandatory": {
     "type": "boolean",
     "notnull": true,
     "default": {
      "kind": "value",
      "value": false
     }
    }
   },
   "pk": [
    "id"
   ],
   "unique": [
    {
     "name": "events_pkey",
     "primary": true,
     "columns": [
      "id"
     ],
     "where": null
    }
   ],
   "fks": [
    {
     "name": "events_created_by_fkey",
     "columns": [
      "created_by"
     ],
     "table": "profiles",
     "refColumns": [
      "id"
     ],
     "onDelete": "no action"
    }
   ],
   "enums": {
    "kind": {
     "constraint": "events_kind_check",
     "values": [
      "build",
      "meeting",
      "competition",
      "potluck",
      "outreach",
      "volunteering",
      "training",
      "other"
     ]
    }
   }
  },
  "feedback": {
   "columns": {
    "id": {
     "type": "uuid",
     "notnull": true,
     "default": {
      "kind": "uuid"
     }
    },
    "member_id": {
     "type": "uuid",
     "notnull": true,
     "default": null
    },
    "category": {
     "type": "text",
     "notnull": true,
     "default": null
    },
    "message": {
     "type": "text",
     "notnull": true,
     "default": null
    },
    "image_paths": {
     "type": "jsonb",
     "notnull": true,
     "default": {
      "kind": "value",
      "value": []
     }
    },
    "route": {
     "type": "text",
     "notnull": false,
     "default": null
    },
    "viewport": {
     "type": "text",
     "notnull": false,
     "default": null
    },
    "user_agent": {
     "type": "text",
     "notnull": false,
     "default": null
    },
    "status": {
     "type": "text",
     "notnull": true,
     "default": {
      "kind": "value",
      "value": "open"
     }
    },
    "reviewed_by": {
     "type": "uuid",
     "notnull": false,
     "default": null
    },
    "reviewed_at": {
     "type": "timestamp with time zone",
     "notnull": false,
     "default": null
    },
    "created_at": {
     "type": "timestamp with time zone",
     "notnull": true,
     "default": {
      "kind": "now"
     }
    }
   },
   "pk": [
    "id"
   ],
   "unique": [
    {
     "name": "feedback_pkey",
     "primary": true,
     "columns": [
      "id"
     ],
     "where": null
    }
   ],
   "fks": [
    {
     "name": "feedback_member_id_fkey",
     "columns": [
      "member_id"
     ],
     "table": "profiles",
     "refColumns": [
      "id"
     ],
     "onDelete": "cascade"
    },
    {
     "name": "feedback_reviewed_by_fkey",
     "columns": [
      "reviewed_by"
     ],
     "table": "profiles",
     "refColumns": [
      "id"
     ],
     "onDelete": "set null"
    }
   ],
   "enums": {
    "category": {
     "constraint": "feedback_category_chk",
     "values": [
      "bug",
      "idea",
      "feedback"
     ]
    },
    "status": {
     "constraint": "feedback_status_chk",
     "values": [
      "open",
      "reviewed",
      "dismissed"
     ]
    }
   }
  },
  "guardian_links": {
   "columns": {
    "parent_id": {
     "type": "uuid",
     "notnull": true,
     "default": null
    },
    "student_id": {
     "type": "uuid",
     "notnull": true,
     "default": null
    },
    "created_by": {
     "type": "uuid",
     "notnull": false,
     "default": null
    },
    "created_at": {
     "type": "timestamp with time zone",
     "notnull": true,
     "default": {
      "kind": "now"
     }
    }
   },
   "pk": [
    "parent_id",
    "student_id"
   ],
   "unique": [
    {
     "name": "guardian_links_pkey",
     "primary": true,
     "columns": [
      "parent_id",
      "student_id"
     ],
     "where": null
    }
   ],
   "fks": [
    {
     "name": "guardian_links_created_by_fkey",
     "columns": [
      "created_by"
     ],
     "table": "profiles",
     "refColumns": [
      "id"
     ],
     "onDelete": "no action"
    },
    {
     "name": "guardian_links_parent_fk",
     "columns": [
      "parent_id"
     ],
     "table": "profiles",
     "refColumns": [
      "id"
     ],
     "onDelete": "cascade"
    },
    {
     "name": "guardian_links_student_fk",
     "columns": [
      "student_id"
     ],
     "table": "profiles",
     "refColumns": [
      "id"
     ],
     "onDelete": "cascade"
    }
   ],
   "enums": {}
  },
  "hour_adjustments": {
   "columns": {
    "id": {
     "type": "uuid",
     "notnull": true,
     "default": {
      "kind": "uuid"
     }
    },
    "member_id": {
     "type": "uuid",
     "notnull": true,
     "default": null
    },
    "category": {
     "type": "text",
     "notnull": true,
     "default": null
    },
    "hours": {
     "type": "numeric",
     "notnull": true,
     "default": null
    },
    "reason": {
     "type": "text",
     "notnull": true,
     "default": null
    },
    "created_by": {
     "type": "uuid",
     "notnull": false,
     "default": null
    },
    "created_at": {
     "type": "timestamp with time zone",
     "notnull": true,
     "default": {
      "kind": "now"
     }
    }
   },
   "pk": [
    "id"
   ],
   "unique": [
    {
     "name": "hour_adjustments_pkey",
     "primary": true,
     "columns": [
      "id"
     ],
     "where": null
    }
   ],
   "fks": [
    {
     "name": "hour_adjustments_created_by_fkey",
     "columns": [
      "created_by"
     ],
     "table": "profiles",
     "refColumns": [
      "id"
     ],
     "onDelete": "no action"
    },
    {
     "name": "hour_adjustments_member_id_fkey",
     "columns": [
      "member_id"
     ],
     "table": "profiles",
     "refColumns": [
      "id"
     ],
     "onDelete": "cascade"
    }
   ],
   "enums": {
    "category": {
     "constraint": "hour_adjustments_category_check",
     "values": [
      "build",
      "outreach",
      "volunteer",
      "competition"
     ]
    }
   }
  },
  "hour_goals": {
   "columns": {
    "id": {
     "type": "uuid",
     "notnull": true,
     "default": {
      "kind": "uuid"
     }
    },
    "member_id": {
     "type": "uuid",
     "notnull": false,
     "default": null
    },
    "season_id": {
     "type": "uuid",
     "notnull": true,
     "default": null
    },
    "target_hours": {
     "type": "numeric(6,2)",
     "notnull": true,
     "default": null
    },
    "categories": {
     "type": "text[]",
     "notnull": false,
     "default": null
    },
    "updated_by": {
     "type": "uuid",
     "notnull": false,
     "default": null
    },
    "updated_at": {
     "type": "timestamp with time zone",
     "notnull": true,
     "default": {
      "kind": "now"
     }
    }
   },
   "pk": [
    "id"
   ],
   "unique": [
    {
     "name": "hour_goals_member_season_uidx",
     "primary": false,
     "columns": [
      "member_id",
      "season_id"
     ],
     "where": {
      "column": "member_id",
      "op": "notnull"
     }
    },
    {
     "name": "hour_goals_pkey",
     "primary": true,
     "columns": [
      "id"
     ],
     "where": null
    },
    {
     "name": "hour_goals_team_season_uidx",
     "primary": false,
     "columns": [
      "season_id"
     ],
     "where": {
      "column": "member_id",
      "op": "null"
     }
    }
   ],
   "fks": [
    {
     "name": "hour_goals_member_id_fkey",
     "columns": [
      "member_id"
     ],
     "table": "profiles",
     "refColumns": [
      "id"
     ],
     "onDelete": "cascade"
    },
    {
     "name": "hour_goals_season_id_fkey",
     "columns": [
      "season_id"
     ],
     "table": "seasons",
     "refColumns": [
      "id"
     ],
     "onDelete": "cascade"
    },
    {
     "name": "hour_goals_updated_by_fkey",
     "columns": [
      "updated_by"
     ],
     "table": "profiles",
     "refColumns": [
      "id"
     ],
     "onDelete": "no action"
    }
   ],
   "enums": {}
  },
  "logged_hours": {
   "columns": {
    "id": {
     "type": "uuid",
     "notnull": true,
     "default": {
      "kind": "uuid"
     }
    },
    "member_id": {
     "type": "uuid",
     "notnull": true,
     "default": null
    },
    "date": {
     "type": "date",
     "notnull": true,
     "default": null
    },
    "hours": {
     "type": "numeric(5,2)",
     "notnull": true,
     "default": null
    },
    "type": {
     "type": "text",
     "notnull": true,
     "default": null
    },
    "description": {
     "type": "text",
     "notnull": false,
     "default": null
    },
    "status": {
     "type": "text",
     "notnull": true,
     "default": {
      "kind": "value",
      "value": "pending"
     }
    },
    "reviewed_by": {
     "type": "uuid",
     "notnull": false,
     "default": null
    },
    "created_at": {
     "type": "timestamp with time zone",
     "notnull": true,
     "default": {
      "kind": "now"
     }
    },
    "verified_by": {
     "type": "uuid",
     "notnull": false,
     "default": null
    },
    "verified_at": {
     "type": "timestamp with time zone",
     "notnull": false,
     "default": null
    }
   },
   "pk": [
    "id"
   ],
   "unique": [
    {
     "name": "logged_hours_pkey",
     "primary": true,
     "columns": [
      "id"
     ],
     "where": null
    }
   ],
   "fks": [
    {
     "name": "logged_hours_member_id_fkey",
     "columns": [
      "member_id"
     ],
     "table": "profiles",
     "refColumns": [
      "id"
     ],
     "onDelete": "cascade"
    },
    {
     "name": "logged_hours_reviewed_by_fkey",
     "columns": [
      "reviewed_by"
     ],
     "table": "profiles",
     "refColumns": [
      "id"
     ],
     "onDelete": "no action"
    },
    {
     "name": "logged_hours_verified_by_fkey",
     "columns": [
      "verified_by"
     ],
     "table": "profiles",
     "refColumns": [
      "id"
     ],
     "onDelete": "no action"
    }
   ],
   "enums": {
    "status": {
     "constraint": "logged_hours_status_check",
     "values": [
      "pending",
      "verified",
      "rejected"
     ]
    },
    "type": {
     "constraint": "logged_hours_type_check",
     "values": [
      "build",
      "outreach",
      "volunteer",
      "competition"
     ]
    }
   }
  },
  "logged_hours_corrections": {
   "columns": {
    "id": {
     "type": "uuid",
     "notnull": true,
     "default": {
      "kind": "uuid"
     }
    },
    "member_id": {
     "type": "uuid",
     "notnull": true,
     "default": null
    },
    "entry_id": {
     "type": "uuid",
     "notnull": true,
     "default": null
    },
    "note": {
     "type": "text",
     "notnull": true,
     "default": null
    },
    "proposed_type": {
     "type": "text",
     "notnull": false,
     "default": null
    },
    "proposed_hours": {
     "type": "numeric",
     "notnull": false,
     "default": null
    },
    "proposed_date": {
     "type": "date",
     "notnull": false,
     "default": null
    },
    "status": {
     "type": "text",
     "notnull": true,
     "default": {
      "kind": "value",
      "value": "pending"
     }
    },
    "resolution_note": {
     "type": "text",
     "notnull": false,
     "default": null
    },
    "reviewed_by": {
     "type": "uuid",
     "notnull": false,
     "default": null
    },
    "reviewed_at": {
     "type": "timestamp with time zone",
     "notnull": false,
     "default": null
    },
    "created_at": {
     "type": "timestamp with time zone",
     "notnull": true,
     "default": {
      "kind": "now"
     }
    }
   },
   "pk": [
    "id"
   ],
   "unique": [
    {
     "name": "lhc_one_pending_per_entry",
     "primary": false,
     "columns": [
      "entry_id"
     ],
     "where": {
      "column": "status",
      "op": "eq",
      "value": "pending"
     }
    },
    {
     "name": "logged_hours_corrections_pkey",
     "primary": true,
     "columns": [
      "id"
     ],
     "where": null
    }
   ],
   "fks": [
    {
     "name": "logged_hours_corrections_entry_id_fkey",
     "columns": [
      "entry_id"
     ],
     "table": "logged_hours",
     "refColumns": [
      "id"
     ],
     "onDelete": "cascade"
    },
    {
     "name": "logged_hours_corrections_member_id_fkey",
     "columns": [
      "member_id"
     ],
     "table": "profiles",
     "refColumns": [
      "id"
     ],
     "onDelete": "cascade"
    },
    {
     "name": "logged_hours_corrections_reviewed_by_fkey",
     "columns": [
      "reviewed_by"
     ],
     "table": "profiles",
     "refColumns": [
      "id"
     ],
     "onDelete": "no action"
    }
   ],
   "enums": {
    "status": {
     "constraint": "logged_hours_corrections_status_check",
     "values": [
      "pending",
      "approved",
      "rejected"
     ]
    }
   }
  },
  "member_applications": {
   "columns": {
    "id": {
     "type": "uuid",
     "notnull": true,
     "default": {
      "kind": "uuid"
     }
    },
    "member_id": {
     "type": "uuid",
     "notnull": true,
     "default": null
    },
    "season_id": {
     "type": "uuid",
     "notnull": true,
     "default": null
    },
    "submitted_at": {
     "type": "timestamp with time zone",
     "notnull": true,
     "default": {
      "kind": "now"
     }
    },
    "legal_first_name": {
     "type": "text",
     "notnull": true,
     "default": null
    },
    "legal_last_name": {
     "type": "text",
     "notnull": true,
     "default": null
    },
    "student_phone": {
     "type": "text",
     "notnull": true,
     "default": null
    },
    "pathway": {
     "type": "text",
     "notnull": true,
     "default": null
    },
    "returning_member": {
     "type": "boolean",
     "notnull": true,
     "default": null
    },
    "seasons_on_team": {
     "type": "integer",
     "notnull": false,
     "default": null
    },
    "prior_robotics": {
     "type": "text[]",
     "notnull": true,
     "default": {
      "kind": "value",
      "value": []
     }
    },
    "programming_languages": {
     "type": "text[]",
     "notnull": true,
     "default": {
      "kind": "value",
      "value": []
     }
    },
    "cad_tools": {
     "type": "text[]",
     "notnull": true,
     "default": {
      "kind": "value",
      "value": []
     }
    },
    "hands_on_experience": {
     "type": "text[]",
     "notnull": true,
     "default": {
      "kind": "value",
      "value": []
     }
    },
    "certifications_claimed": {
     "type": "text",
     "notnull": false,
     "default": null
    },
    "subteam_first": {
     "type": "text",
     "notnull": true,
     "default": null
    },
    "subteam_second": {
     "type": "text",
     "notnull": true,
     "default": null
    },
    "subteam_third": {
     "type": "text",
     "notnull": false,
     "default": null
    },
    "subteam_rationale": {
     "type": "text",
     "notnull": true,
     "default": null
    },
    "monday_lunch": {
     "type": "text",
     "notnull": true,
     "default": null
    },
    "tuesday_after_school": {
     "type": "text",
     "notnull": true,
     "default": null
    },
    "friday_after_school": {
     "type": "text",
     "notnull": true,
     "default": null
    },
    "transport_after_5pm": {
     "type": "text",
     "notnull": true,
     "default": null
    },
    "seasonal_conflicts": {
     "type": "text[]",
     "notnull": true,
     "default": {
      "kind": "value",
      "value": []
     }
    },
    "conflict_detail": {
     "type": "text",
     "notnull": false,
     "default": null
    },
    "fll_volunteering_interest": {
     "type": "text",
     "notnull": false,
     "default": null
    },
    "build_season_acknowledged": {
     "type": "boolean",
     "notnull": true,
     "default": null
    },
    "parent_name": {
     "type": "text",
     "notnull": true,
     "default": null
    },
    "parent_email": {
     "type": "text",
     "notnull": true,
     "default": null
    },
    "parent_phone": {
     "type": "text",
     "notnull": true,
     "default": null
    },
    "parent_two_name": {
     "type": "text",
     "notnull": false,
     "default": null
    },
    "parent_two_contact": {
     "type": "text",
     "notnull": false,
     "default": null
    },
    "dietary_restrictions": {
     "type": "text",
     "notnull": false,
     "default": null
    },
    "emergency_contact_name": {
     "type": "text",
     "notnull": true,
     "default": null
    },
    "emergency_contact_phone": {
     "type": "text",
     "notnull": true,
     "default": null
    },
    "discord_username": {
     "type": "text",
     "notnull": true,
     "default": null
    },
    "discord_server_confirmed": {
     "type": "boolean",
     "notnull": true,
     "default": {
      "kind": "value",
      "value": false
     }
    },
    "conduct_acknowledged": {
     "type": "boolean",
     "notnull": true,
     "default": null
    },
    "parent_token": {
     "type": "uuid",
     "notnull": true,
     "default": {
      "kind": "uuid"
     },
     "noSelect": true
    }
   },
   "pk": [
    "id"
   ],
   "unique": [
    {
     "name": "member_applications_member_season_uniq",
     "primary": false,
     "columns": [
      "member_id",
      "season_id"
     ],
     "where": null
    },
    {
     "name": "member_applications_parent_token_key",
     "primary": false,
     "columns": [
      "parent_token"
     ],
     "where": null
    },
    {
     "name": "member_applications_pkey",
     "primary": true,
     "columns": [
      "id"
     ],
     "where": null
    }
   ],
   "fks": [
    {
     "name": "member_applications_member_id_fkey",
     "columns": [
      "member_id"
     ],
     "table": "profiles",
     "refColumns": [
      "id"
     ],
     "onDelete": "cascade"
    },
    {
     "name": "member_applications_season_id_fkey",
     "columns": [
      "season_id"
     ],
     "table": "seasons",
     "refColumns": [
      "id"
     ],
     "onDelete": "restrict"
    }
   ],
   "enums": {
    "monday_lunch": {
     "constraint": "member_applications_availability_chk",
     "values": [
      "Yes",
      "No",
      "Sometimes"
     ]
    },
    "tuesday_after_school": {
     "constraint": "member_applications_availability_chk",
     "values": [
      "Yes",
      "No",
      "Sometimes"
     ]
    },
    "friday_after_school": {
     "constraint": "member_applications_availability_chk",
     "values": [
      "Yes",
      "No",
      "Sometimes"
     ]
    },
    "pathway": {
     "constraint": "member_applications_pathway_chk",
     "values": [
      "CSEE",
      "MSET",
      "MAT",
      "IDEA",
      "ACE",
      "BMET",
      "Freshman - in rotation"
     ]
    },
    "subteam_first": {
     "constraint": "member_applications_subteam_values_chk",
     "values": [
      "Mechanical",
      "Electrical",
      "Programming",
      "CAD",
      "Fabrication",
      "Media",
      "Business/Outreach",
      "Drive Team",
      "Robot Construction",
      "Field & Pit",
      "Strategy and Scouting",
      "Management"
     ]
    },
    "subteam_second": {
     "constraint": "member_applications_subteam_values_chk",
     "values": [
      "Mechanical",
      "Electrical",
      "Programming",
      "CAD",
      "Fabrication",
      "Media",
      "Business/Outreach",
      "Drive Team",
      "Robot Construction",
      "Field & Pit",
      "Strategy and Scouting",
      "Management"
     ]
    },
    "subteam_third": {
     "constraint": "member_applications_subteam_values_chk",
     "values": [
      "Mechanical",
      "Electrical",
      "Programming",
      "CAD",
      "Fabrication",
      "Media",
      "Business/Outreach",
      "Drive Team",
      "Robot Construction",
      "Field & Pit",
      "Strategy and Scouting",
      "Management"
     ]
    }
   }
  },
  "member_roles": {
   "columns": {
    "member_id": {
     "type": "uuid",
     "notnull": true,
     "default": null
    },
    "role": {
     "type": "text",
     "notnull": true,
     "default": null
    }
   },
   "pk": [
    "member_id",
    "role"
   ],
   "unique": [
    {
     "name": "member_roles_pkey",
     "primary": true,
     "columns": [
      "member_id",
      "role"
     ],
     "where": null
    }
   ],
   "fks": [
    {
     "name": "member_roles_member_id_fkey",
     "columns": [
      "member_id"
     ],
     "table": "profiles",
     "refColumns": [
      "id"
     ],
     "onDelete": "cascade"
    }
   ],
   "enums": {
    "role": {
     "constraint": "member_roles_role_chk",
     "values": [
      "student",
      "mentor",
      "lead",
      "admin",
      "parent"
     ]
    }
   }
  },
  "member_skills": {
   "columns": {
    "member_id": {
     "type": "uuid",
     "notnull": true,
     "default": null
    },
    "skill_id": {
     "type": "uuid",
     "notnull": true,
     "default": null
    },
    "status": {
     "type": "text",
     "notnull": true,
     "default": null
    },
    "certified_by": {
     "type": "uuid",
     "notnull": false,
     "default": null
    },
    "updated_at": {
     "type": "timestamp with time zone",
     "notnull": true,
     "default": {
      "kind": "now"
     }
    },
    "certified_at": {
     "type": "timestamp with time zone",
     "notnull": false,
     "default": null
    }
   },
   "pk": [
    "member_id",
    "skill_id"
   ],
   "unique": [
    {
     "name": "member_skills_pkey",
     "primary": true,
     "columns": [
      "member_id",
      "skill_id"
     ],
     "where": null
    }
   ],
   "fks": [
    {
     "name": "member_skills_certified_by_fkey",
     "columns": [
      "certified_by"
     ],
     "table": "profiles",
     "refColumns": [
      "id"
     ],
     "onDelete": "set null"
    },
    {
     "name": "member_skills_member_id_fkey",
     "columns": [
      "member_id"
     ],
     "table": "profiles",
     "refColumns": [
      "id"
     ],
     "onDelete": "cascade"
    },
    {
     "name": "member_skills_skill_id_fkey",
     "columns": [
      "skill_id"
     ],
     "table": "skills",
     "refColumns": [
      "id"
     ],
     "onDelete": "cascade"
    }
   ],
   "enums": {
    "status": {
     "constraint": "member_skills_status_check",
     "values": [
      "in_progress",
      "certified"
     ]
    }
   }
  },
  "notifications_sent": {
   "columns": {
    "member_id": {
     "type": "uuid",
     "notnull": true,
     "default": null
    },
    "kind": {
     "type": "text",
     "notnull": true,
     "default": null
    },
    "ref_id": {
     "type": "text",
     "notnull": true,
     "default": null
    },
    "sent_at": {
     "type": "timestamp with time zone",
     "notnull": true,
     "default": {
      "kind": "now"
     }
    }
   },
   "pk": [
    "member_id",
    "kind",
    "ref_id"
   ],
   "unique": [
    {
     "name": "notifications_sent_pkey",
     "primary": true,
     "columns": [
      "member_id",
      "kind",
      "ref_id"
     ],
     "where": null
    }
   ],
   "fks": [
    {
     "name": "notifications_sent_member_id_fkey",
     "columns": [
      "member_id"
     ],
     "table": "profiles",
     "refColumns": [
      "id"
     ],
     "onDelete": "cascade"
    }
   ],
   "enums": {}
  },
  "parent_link_requests": {
   "columns": {
    "id": {
     "type": "uuid",
     "notnull": true,
     "default": {
      "kind": "uuid"
     }
    },
    "parent_id": {
     "type": "uuid",
     "notnull": true,
     "default": null
    },
    "student_id": {
     "type": "uuid",
     "notnull": true,
     "default": null
    },
    "note": {
     "type": "text",
     "notnull": false,
     "default": null
    },
    "status": {
     "type": "text",
     "notnull": true,
     "default": {
      "kind": "value",
      "value": "pending"
     }
    },
    "reviewed_by": {
     "type": "uuid",
     "notnull": false,
     "default": null
    },
    "reviewed_at": {
     "type": "timestamp with time zone",
     "notnull": false,
     "default": null
    },
    "created_at": {
     "type": "timestamp with time zone",
     "notnull": true,
     "default": {
      "kind": "now"
     }
    }
   },
   "pk": [
    "id"
   ],
   "unique": [
    {
     "name": "parent_link_requests_one_pending",
     "primary": false,
     "columns": [
      "parent_id",
      "student_id"
     ],
     "where": {
      "column": "status",
      "op": "eq",
      "value": "pending"
     }
    },
    {
     "name": "parent_link_requests_pkey",
     "primary": true,
     "columns": [
      "id"
     ],
     "where": null
    }
   ],
   "fks": [
    {
     "name": "parent_link_requests_parent_id_fkey",
     "columns": [
      "parent_id"
     ],
     "table": "profiles",
     "refColumns": [
      "id"
     ],
     "onDelete": "cascade"
    },
    {
     "name": "parent_link_requests_reviewed_by_fkey",
     "columns": [
      "reviewed_by"
     ],
     "table": "profiles",
     "refColumns": [
      "id"
     ],
     "onDelete": "no action"
    },
    {
     "name": "parent_link_requests_student_id_fkey",
     "columns": [
      "student_id"
     ],
     "table": "profiles",
     "refColumns": [
      "id"
     ],
     "onDelete": "cascade"
    }
   ],
   "enums": {
    "status": {
     "constraint": "parent_link_requests_status_check",
     "values": [
      "pending",
      "approved",
      "denied"
     ]
    }
   }
  },
  "parent_responses": {
   "columns": {
    "id": {
     "type": "uuid",
     "notnull": true,
     "default": {
      "kind": "uuid"
     }
    },
    "application_id": {
     "type": "uuid",
     "notnull": true,
     "default": null
    },
    "weekend_supervision": {
     "type": "text",
     "notnull": false,
     "default": null
    },
    "meal_support": {
     "type": "text",
     "notnull": false,
     "default": null
    },
    "travel_driving": {
     "type": "text",
     "notnull": false,
     "default": null
    },
    "employer_name": {
     "type": "text",
     "notnull": false,
     "default": null
    },
    "employer_contact_consent": {
     "type": "boolean",
     "notnull": true,
     "default": {
      "kind": "value",
      "value": false
     }
    },
    "donation_offer": {
     "type": "text",
     "notnull": false,
     "default": null
    },
    "submitted_at": {
     "type": "timestamp with time zone",
     "notnull": true,
     "default": {
      "kind": "now"
     }
    },
    "updated_at": {
     "type": "timestamp with time zone",
     "notnull": false,
     "default": null
    }
   },
   "pk": [
    "id"
   ],
   "unique": [
    {
     "name": "parent_responses_application_uniq",
     "primary": false,
     "columns": [
      "application_id"
     ],
     "where": null
    },
    {
     "name": "parent_responses_pkey",
     "primary": true,
     "columns": [
      "id"
     ],
     "where": null
    }
   ],
   "fks": [
    {
     "name": "parent_responses_application_id_fkey",
     "columns": [
      "application_id"
     ],
     "table": "member_applications",
     "refColumns": [
      "id"
     ],
     "onDelete": "cascade"
    }
   ],
   "enums": {
    "meal_support": {
     "constraint": "parent_responses_meal_chk",
     "values": [
      "yes",
      "no",
      "maybe"
     ]
    },
    "travel_driving": {
     "constraint": "parent_responses_travel_chk",
     "values": [
      "yes",
      "no",
      "maybe"
     ]
    },
    "weekend_supervision": {
     "constraint": "parent_responses_weekend_chk",
     "values": [
      "saturdays",
      "sundays",
      "either",
      "neither"
     ]
    }
   }
  },
  "position_assignments": {
   "columns": {
    "position_id": {
     "type": "uuid",
     "notnull": true,
     "default": null
    },
    "member_id": {
     "type": "uuid",
     "notnull": true,
     "default": null
    },
    "assigned_by": {
     "type": "uuid",
     "notnull": false,
     "default": null
    },
    "assigned_at": {
     "type": "timestamp with time zone",
     "notnull": true,
     "default": {
      "kind": "now"
     }
    }
   },
   "pk": [
    "position_id",
    "member_id"
   ],
   "unique": [
    {
     "name": "position_assignments_pkey",
     "primary": true,
     "columns": [
      "position_id",
      "member_id"
     ],
     "where": null
    }
   ],
   "fks": [
    {
     "name": "position_assignments_assigned_by_fkey",
     "columns": [
      "assigned_by"
     ],
     "table": "profiles",
     "refColumns": [
      "id"
     ],
     "onDelete": "no action"
    },
    {
     "name": "position_assignments_member_id_fkey",
     "columns": [
      "member_id"
     ],
     "table": "profiles",
     "refColumns": [
      "id"
     ],
     "onDelete": "cascade"
    },
    {
     "name": "position_assignments_position_id_fkey",
     "columns": [
      "position_id"
     ],
     "table": "positions",
     "refColumns": [
      "id"
     ],
     "onDelete": "cascade"
    }
   ],
   "enums": {}
  },
  "positions": {
   "columns": {
    "id": {
     "type": "uuid",
     "notnull": true,
     "default": {
      "kind": "uuid"
     }
    },
    "name": {
     "type": "text",
     "notnull": true,
     "default": null
    },
    "description": {
     "type": "text",
     "notnull": false,
     "default": null
    },
    "target_count": {
     "type": "integer",
     "notnull": true,
     "default": {
      "kind": "value",
      "value": 1
     }
    },
    "sort_order": {
     "type": "integer",
     "notnull": true,
     "default": {
      "kind": "value",
      "value": 0
     }
    },
    "created_at": {
     "type": "timestamp with time zone",
     "notnull": true,
     "default": {
      "kind": "now"
     }
    }
   },
   "pk": [
    "id"
   ],
   "unique": [
    {
     "name": "positions_name_key",
     "primary": false,
     "columns": [
      "name"
     ],
     "where": null
    },
    {
     "name": "positions_pkey",
     "primary": true,
     "columns": [
      "id"
     ],
     "where": null
    }
   ],
   "fks": [],
   "enums": {}
  },
  "profiles": {
   "columns": {
    "id": {
     "type": "uuid",
     "notnull": true,
     "default": null
    },
    "full_name": {
     "type": "text",
     "notnull": false,
     "default": null
    },
    "nickname": {
     "type": "text",
     "notnull": false,
     "default": null
    },
    "avatar_url": {
     "type": "text",
     "notnull": false,
     "default": null
    },
    "bio": {
     "type": "text",
     "notnull": false,
     "default": null
    },
    "approved": {
     "type": "boolean",
     "notnull": true,
     "default": {
      "kind": "value",
      "value": false
     }
    },
    "created_at": {
     "type": "timestamp with time zone",
     "notnull": true,
     "default": {
      "kind": "now"
     }
    },
    "grad_year": {
     "type": "integer",
     "notnull": false,
     "default": null
    },
    "status": {
     "type": "text",
     "notnull": true,
     "default": {
      "kind": "value",
      "value": "active"
     }
    },
    "shirt_size": {
     "type": "text",
     "notnull": false,
     "default": null
    },
    "subteams": {
     "type": "text[]",
     "notnull": true,
     "default": {
      "kind": "value",
      "value": []
     }
    },
    "onboarded_at": {
     "type": "timestamp with time zone",
     "notnull": false,
     "default": null
    },
    "disciplines": {
     "type": "text[]",
     "notnull": true,
     "default": {
      "kind": "value",
      "value": []
     }
    },
    "calendar_token": {
     "type": "uuid",
     "notnull": true,
     "default": {
      "kind": "uuid"
     }
    },
    "notification_prefs": {
     "type": "jsonb",
     "notnull": true,
     "default": {
      "kind": "value",
      "value": {
       "enabled": true,
       "quiet_hours": {
        "end": "07:00",
        "start": "21:00"
       },
       "shop_status": false,
       "task_signoff": true,
       "announcements": true,
       "parent_digest": true,
       "skill_signoff": true,
       "event_reminder": true,
       "job_assignment": true,
       "schedule_change": true,
       "checkin_reminder": false
      }
     }
    },
    "geofence_exempt": {
     "type": "boolean",
     "notnull": true,
     "default": {
      "kind": "value",
      "value": false
     }
    }
   },
   "pk": [
    "id"
   ],
   "unique": [
    {
     "name": "profiles_calendar_token_key",
     "primary": false,
     "columns": [
      "calendar_token"
     ],
     "where": null
    },
    {
     "name": "profiles_pkey",
     "primary": true,
     "columns": [
      "id"
     ],
     "where": null
    }
   ],
   "fks": [
    {
     "name": "profiles_id_fkey",
     "columns": [
      "id"
     ],
     "table": "auth.users",
     "refColumns": [
      "id"
     ],
     "onDelete": "cascade"
    }
   ],
   "enums": {
    "status": {
     "constraint": "profiles_status_chk",
     "values": [
      "active",
      "inactive",
      "alumni"
     ]
    }
   }
  },
  "push_subscriptions": {
   "columns": {
    "endpoint": {
     "type": "text",
     "notnull": true,
     "default": null
    },
    "member_id": {
     "type": "uuid",
     "notnull": true,
     "default": null
    },
    "p256dh": {
     "type": "text",
     "notnull": true,
     "default": null
    },
    "auth": {
     "type": "text",
     "notnull": true,
     "default": null
    },
    "user_agent": {
     "type": "text",
     "notnull": false,
     "default": null
    },
    "created_at": {
     "type": "timestamp with time zone",
     "notnull": true,
     "default": {
      "kind": "now"
     }
    }
   },
   "pk": [
    "endpoint"
   ],
   "unique": [
    {
     "name": "push_subscriptions_pkey",
     "primary": true,
     "columns": [
      "endpoint"
     ],
     "where": null
    }
   ],
   "fks": [
    {
     "name": "push_subscriptions_member_id_fkey",
     "columns": [
      "member_id"
     ],
     "table": "profiles",
     "refColumns": [
      "id"
     ],
     "onDelete": "cascade"
    }
   ],
   "enums": {}
  },
  "seasons": {
   "columns": {
    "id": {
     "type": "uuid",
     "notnull": true,
     "default": {
      "kind": "uuid"
     }
    },
    "name": {
     "type": "text",
     "notnull": true,
     "default": null
    },
    "start_date": {
     "type": "date",
     "notnull": true,
     "default": null
    },
    "end_date": {
     "type": "date",
     "notnull": true,
     "default": null
    },
    "created_at": {
     "type": "timestamp with time zone",
     "notnull": true,
     "default": {
      "kind": "now"
     }
    }
   },
   "pk": [
    "id"
   ],
   "unique": [
    {
     "name": "seasons_pkey",
     "primary": true,
     "columns": [
      "id"
     ],
     "where": null
    }
   ],
   "fks": [],
   "enums": {}
  },
  "session_corrections": {
   "columns": {
    "id": {
     "type": "uuid",
     "notnull": true,
     "default": {
      "kind": "uuid"
     }
    },
    "member_id": {
     "type": "uuid",
     "notnull": true,
     "default": null
    },
    "checkin_id": {
     "type": "uuid",
     "notnull": false,
     "default": null
    },
    "checkout_id": {
     "type": "uuid",
     "notnull": false,
     "default": null
    },
    "note": {
     "type": "text",
     "notnull": true,
     "default": null
    },
    "proposed_in": {
     "type": "timestamp with time zone",
     "notnull": false,
     "default": null
    },
    "proposed_out": {
     "type": "timestamp with time zone",
     "notnull": false,
     "default": null
    },
    "proposed_category": {
     "type": "text",
     "notnull": false,
     "default": null
    },
    "status": {
     "type": "text",
     "notnull": true,
     "default": {
      "kind": "value",
      "value": "pending"
     }
    },
    "resolution_note": {
     "type": "text",
     "notnull": false,
     "default": null
    },
    "reviewed_by": {
     "type": "uuid",
     "notnull": false,
     "default": null
    },
    "reviewed_at": {
     "type": "timestamp with time zone",
     "notnull": false,
     "default": null
    },
    "created_at": {
     "type": "timestamp with time zone",
     "notnull": true,
     "default": {
      "kind": "now"
     }
    }
   },
   "pk": [
    "id"
   ],
   "unique": [
    {
     "name": "session_corrections_pkey",
     "primary": true,
     "columns": [
      "id"
     ],
     "where": null
    }
   ],
   "fks": [
    {
     "name": "session_corrections_checkin_id_fkey",
     "columns": [
      "checkin_id"
     ],
     "table": "attendance_events",
     "refColumns": [
      "id"
     ],
     "onDelete": "set null"
    },
    {
     "name": "session_corrections_checkout_id_fkey",
     "columns": [
      "checkout_id"
     ],
     "table": "attendance_events",
     "refColumns": [
      "id"
     ],
     "onDelete": "set null"
    },
    {
     "name": "session_corrections_member_id_fkey",
     "columns": [
      "member_id"
     ],
     "table": "profiles",
     "refColumns": [
      "id"
     ],
     "onDelete": "cascade"
    },
    {
     "name": "session_corrections_reviewed_by_fkey",
     "columns": [
      "reviewed_by"
     ],
     "table": "profiles",
     "refColumns": [
      "id"
     ],
     "onDelete": "no action"
    }
   ],
   "enums": {
    "status": {
     "constraint": "session_corrections_status_check",
     "values": [
      "pending",
      "approved",
      "rejected"
     ]
    }
   }
  },
  "session_reviews": {
   "columns": {
    "id": {
     "type": "uuid",
     "notnull": true,
     "default": {
      "kind": "uuid"
     }
    },
    "user_id": {
     "type": "uuid",
     "notnull": true,
     "default": null
    },
    "checkin_id": {
     "type": "uuid",
     "notnull": true,
     "default": null
    },
    "checkout_id": {
     "type": "uuid",
     "notnull": true,
     "default": null
    },
    "status": {
     "type": "text",
     "notnull": true,
     "default": {
      "kind": "value",
      "value": "pending"
     }
    },
    "reviewed_by": {
     "type": "uuid",
     "notnull": false,
     "default": null
    },
    "reviewed_at": {
     "type": "timestamp with time zone",
     "notnull": false,
     "default": null
    },
    "created_at": {
     "type": "timestamp with time zone",
     "notnull": false,
     "default": {
      "kind": "now"
     }
    }
   },
   "pk": [
    "id"
   ],
   "unique": [
    {
     "name": "session_reviews_checkin_id_key",
     "primary": false,
     "columns": [
      "checkin_id"
     ],
     "where": null
    },
    {
     "name": "session_reviews_checkout_id_key",
     "primary": false,
     "columns": [
      "checkout_id"
     ],
     "where": null
    },
    {
     "name": "session_reviews_pkey",
     "primary": true,
     "columns": [
      "id"
     ],
     "where": null
    }
   ],
   "fks": [
    {
     "name": "session_reviews_checkin_id_fkey",
     "columns": [
      "checkin_id"
     ],
     "table": "attendance_events",
     "refColumns": [
      "id"
     ],
     "onDelete": "cascade"
    },
    {
     "name": "session_reviews_checkout_id_fkey",
     "columns": [
      "checkout_id"
     ],
     "table": "attendance_events",
     "refColumns": [
      "id"
     ],
     "onDelete": "cascade"
    },
    {
     "name": "session_reviews_reviewed_by_fkey",
     "columns": [
      "reviewed_by"
     ],
     "table": "auth.users",
     "refColumns": [
      "id"
     ],
     "onDelete": "no action"
    },
    {
     "name": "session_reviews_user_id_fkey",
     "columns": [
      "user_id"
     ],
     "table": "auth.users",
     "refColumns": [
      "id"
     ],
     "onDelete": "cascade"
    }
   ],
   "enums": {
    "status": {
     "constraint": "session_reviews_status_check",
     "values": [
      "pending",
      "approved",
      "voided"
     ]
    }
   }
  },
  "skills": {
   "columns": {
    "id": {
     "type": "uuid",
     "notnull": true,
     "default": {
      "kind": "uuid"
     }
    },
    "name": {
     "type": "text",
     "notnull": true,
     "default": null
    },
    "category": {
     "type": "text",
     "notnull": true,
     "default": {
      "kind": "value",
      "value": "General"
     }
    },
    "description": {
     "type": "text",
     "notnull": false,
     "default": null
    },
    "safety_critical": {
     "type": "boolean",
     "notnull": true,
     "default": {
      "kind": "value",
      "value": false
     }
    },
    "sort_order": {
     "type": "integer",
     "notnull": true,
     "default": {
      "kind": "value",
      "value": 0
     }
    },
    "created_at": {
     "type": "timestamp with time zone",
     "notnull": true,
     "default": {
      "kind": "now"
     }
    }
   },
   "pk": [
    "id"
   ],
   "unique": [
    {
     "name": "skills_pkey",
     "primary": true,
     "columns": [
      "id"
     ],
     "where": null
    }
   ],
   "fks": [],
   "enums": {}
  },
  "study_sessions": {
   "columns": {
    "id": {
     "type": "uuid",
     "notnull": true,
     "default": {
      "kind": "uuid"
     }
    },
    "member_id": {
     "type": "uuid",
     "notnull": true,
     "default": null
    },
    "date": {
     "type": "date",
     "notnull": true,
     "default": null
    },
    "minutes": {
     "type": "integer",
     "notnull": true,
     "default": null
    },
    "note": {
     "type": "text",
     "notnull": false,
     "default": null
    },
    "created_at": {
     "type": "timestamp with time zone",
     "notnull": true,
     "default": {
      "kind": "now"
     }
    }
   },
   "pk": [
    "id"
   ],
   "unique": [
    {
     "name": "study_sessions_pkey",
     "primary": true,
     "columns": [
      "id"
     ],
     "where": null
    }
   ],
   "fks": [
    {
     "name": "study_sessions_member_id_fkey",
     "columns": [
      "member_id"
     ],
     "table": "profiles",
     "refColumns": [
      "id"
     ],
     "onDelete": "cascade"
    }
   ],
   "enums": {}
  },
  "survey_answers": {
   "columns": {
    "id": {
     "type": "uuid",
     "notnull": true,
     "default": {
      "kind": "uuid"
     }
    },
    "response_id": {
     "type": "uuid",
     "notnull": true,
     "default": null
    },
    "question_id": {
     "type": "uuid",
     "notnull": true,
     "default": null
    },
    "value": {
     "type": "jsonb",
     "notnull": true,
     "default": null
    }
   },
   "pk": [
    "id"
   ],
   "unique": [
    {
     "name": "survey_answers_once",
     "primary": false,
     "columns": [
      "response_id",
      "question_id"
     ],
     "where": null
    },
    {
     "name": "survey_answers_pkey",
     "primary": true,
     "columns": [
      "id"
     ],
     "where": null
    }
   ],
   "fks": [
    {
     "name": "survey_answers_question_id_fkey",
     "columns": [
      "question_id"
     ],
     "table": "survey_questions",
     "refColumns": [
      "id"
     ],
     "onDelete": "cascade"
    },
    {
     "name": "survey_answers_response_id_fkey",
     "columns": [
      "response_id"
     ],
     "table": "survey_responses",
     "refColumns": [
      "id"
     ],
     "onDelete": "cascade"
    }
   ],
   "enums": {}
  },
  "survey_questions": {
   "columns": {
    "id": {
     "type": "uuid",
     "notnull": true,
     "default": {
      "kind": "uuid"
     }
    },
    "survey_id": {
     "type": "uuid",
     "notnull": true,
     "default": null
    },
    "position": {
     "type": "integer",
     "notnull": true,
     "default": {
      "kind": "value",
      "value": 0
     }
    },
    "kind": {
     "type": "text",
     "notnull": true,
     "default": null
    },
    "prompt": {
     "type": "text",
     "notnull": true,
     "default": null
    },
    "options": {
     "type": "jsonb",
     "notnull": true,
     "default": {
      "kind": "value",
      "value": []
     }
    },
    "required": {
     "type": "boolean",
     "notnull": true,
     "default": {
      "kind": "value",
      "value": false
     }
    },
    "created_at": {
     "type": "timestamp with time zone",
     "notnull": true,
     "default": {
      "kind": "now"
     }
    }
   },
   "pk": [
    "id"
   ],
   "unique": [
    {
     "name": "survey_questions_pkey",
     "primary": true,
     "columns": [
      "id"
     ],
     "where": null
    }
   ],
   "fks": [
    {
     "name": "survey_questions_survey_id_fkey",
     "columns": [
      "survey_id"
     ],
     "table": "surveys",
     "refColumns": [
      "id"
     ],
     "onDelete": "cascade"
    }
   ],
   "enums": {
    "kind": {
     "constraint": "survey_questions_kind_chk",
     "values": [
      "single",
      "multi",
      "scale",
      "text"
     ]
    }
   }
  },
  "survey_responses": {
   "columns": {
    "id": {
     "type": "uuid",
     "notnull": true,
     "default": {
      "kind": "uuid"
     }
    },
    "survey_id": {
     "type": "uuid",
     "notnull": true,
     "default": null
    },
    "member_id": {
     "type": "uuid",
     "notnull": true,
     "default": null
    },
    "submitted_at": {
     "type": "timestamp with time zone",
     "notnull": true,
     "default": {
      "kind": "now"
     }
    }
   },
   "pk": [
    "id"
   ],
   "unique": [
    {
     "name": "survey_responses_once",
     "primary": false,
     "columns": [
      "survey_id",
      "member_id"
     ],
     "where": null
    },
    {
     "name": "survey_responses_pkey",
     "primary": true,
     "columns": [
      "id"
     ],
     "where": null
    }
   ],
   "fks": [
    {
     "name": "survey_responses_member_id_fkey",
     "columns": [
      "member_id"
     ],
     "table": "profiles",
     "refColumns": [
      "id"
     ],
     "onDelete": "cascade"
    },
    {
     "name": "survey_responses_survey_id_fkey",
     "columns": [
      "survey_id"
     ],
     "table": "surveys",
     "refColumns": [
      "id"
     ],
     "onDelete": "cascade"
    }
   ],
   "enums": {}
  },
  "surveys": {
   "columns": {
    "id": {
     "type": "uuid",
     "notnull": true,
     "default": {
      "kind": "uuid"
     }
    },
    "title": {
     "type": "text",
     "notnull": true,
     "default": null
    },
    "opens_at": {
     "type": "timestamp with time zone",
     "notnull": false,
     "default": null
    },
    "closes_at": {
     "type": "timestamp with time zone",
     "notnull": false,
     "default": null
    },
    "is_open": {
     "type": "boolean",
     "notnull": true,
     "default": {
      "kind": "value",
      "value": false
     }
    },
    "created_by": {
     "type": "uuid",
     "notnull": false,
     "default": null
    },
    "created_at": {
     "type": "timestamp with time zone",
     "notnull": true,
     "default": {
      "kind": "now"
     }
    }
   },
   "pk": [
    "id"
   ],
   "unique": [
    {
     "name": "surveys_one_open_idx",
     "primary": false,
     "columns": [],
     "where": {
      "column": "is_open",
      "op": "eq",
      "value": true
     }
    },
    {
     "name": "surveys_pkey",
     "primary": true,
     "columns": [
      "id"
     ],
     "where": null
    }
   ],
   "fks": [
    {
     "name": "surveys_created_by_fkey",
     "columns": [
      "created_by"
     ],
     "table": "profiles",
     "refColumns": [
      "id"
     ],
     "onDelete": "set null"
    }
   ],
   "enums": {}
  },
  "task_claims": {
   "columns": {
    "task_id": {
     "type": "uuid",
     "notnull": true,
     "default": null
    },
    "member_id": {
     "type": "uuid",
     "notnull": true,
     "default": null
    },
    "status": {
     "type": "text",
     "notnull": true,
     "default": {
      "kind": "value",
      "value": "claimed"
     }
    },
    "claimed_at": {
     "type": "timestamp with time zone",
     "notnull": true,
     "default": {
      "kind": "now"
     }
    },
    "submitted_at": {
     "type": "timestamp with time zone",
     "notnull": false,
     "default": null
    },
    "verified_by": {
     "type": "uuid",
     "notnull": false,
     "default": null
    },
    "verified_at": {
     "type": "timestamp with time zone",
     "notnull": false,
     "default": null
    }
   },
   "pk": [
    "task_id",
    "member_id"
   ],
   "unique": [
    {
     "name": "task_claims_pkey",
     "primary": true,
     "columns": [
      "task_id",
      "member_id"
     ],
     "where": null
    }
   ],
   "fks": [
    {
     "name": "task_claims_member_id_fkey",
     "columns": [
      "member_id"
     ],
     "table": "profiles",
     "refColumns": [
      "id"
     ],
     "onDelete": "cascade"
    },
    {
     "name": "task_claims_task_id_fkey",
     "columns": [
      "task_id"
     ],
     "table": "tasks",
     "refColumns": [
      "id"
     ],
     "onDelete": "cascade"
    },
    {
     "name": "task_claims_verified_by_fkey",
     "columns": [
      "verified_by"
     ],
     "table": "profiles",
     "refColumns": [
      "id"
     ],
     "onDelete": "no action"
    }
   ],
   "enums": {
    "status": {
     "constraint": "task_claims_status_check",
     "values": [
      "claimed",
      "submitted",
      "completed"
     ]
    }
   }
  },
  "task_required_skills": {
   "columns": {
    "task_id": {
     "type": "uuid",
     "notnull": true,
     "default": null
    },
    "skill_id": {
     "type": "uuid",
     "notnull": true,
     "default": null
    }
   },
   "pk": [
    "task_id",
    "skill_id"
   ],
   "unique": [
    {
     "name": "task_required_skills_pkey",
     "primary": true,
     "columns": [
      "task_id",
      "skill_id"
     ],
     "where": null
    }
   ],
   "fks": [
    {
     "name": "task_required_skills_skill_id_fkey",
     "columns": [
      "skill_id"
     ],
     "table": "skills",
     "refColumns": [
      "id"
     ],
     "onDelete": "cascade"
    },
    {
     "name": "task_required_skills_task_id_fkey",
     "columns": [
      "task_id"
     ],
     "table": "tasks",
     "refColumns": [
      "id"
     ],
     "onDelete": "cascade"
    }
   ],
   "enums": {}
  },
  "task_updates": {
   "columns": {
    "id": {
     "type": "uuid",
     "notnull": true,
     "default": {
      "kind": "uuid"
     }
    },
    "task_id": {
     "type": "uuid",
     "notnull": true,
     "default": null
    },
    "member_id": {
     "type": "uuid",
     "notnull": true,
     "default": null
    },
    "body": {
     "type": "text",
     "notnull": false,
     "default": null
    },
    "image_path": {
     "type": "text",
     "notnull": false,
     "default": null
    },
    "created_at": {
     "type": "timestamp with time zone",
     "notnull": true,
     "default": {
      "kind": "now"
     }
    }
   },
   "pk": [
    "id"
   ],
   "unique": [
    {
     "name": "task_updates_pkey",
     "primary": true,
     "columns": [
      "id"
     ],
     "where": null
    }
   ],
   "fks": [
    {
     "name": "task_updates_member_id_fkey",
     "columns": [
      "member_id"
     ],
     "table": "profiles",
     "refColumns": [
      "id"
     ],
     "onDelete": "cascade"
    },
    {
     "name": "task_updates_task_id_fkey",
     "columns": [
      "task_id"
     ],
     "table": "tasks",
     "refColumns": [
      "id"
     ],
     "onDelete": "cascade"
    }
   ],
   "enums": {}
  },
  "tasks": {
   "columns": {
    "id": {
     "type": "uuid",
     "notnull": true,
     "default": {
      "kind": "uuid"
     }
    },
    "title": {
     "type": "text",
     "notnull": true,
     "default": null
    },
    "description": {
     "type": "text",
     "notnull": false,
     "default": null
    },
    "subteam": {
     "type": "text",
     "notnull": false,
     "default": null
    },
    "status": {
     "type": "text",
     "notnull": true,
     "default": {
      "kind": "value",
      "value": "open"
     }
    },
    "claimed_by": {
     "type": "uuid",
     "notnull": false,
     "default": null
    },
    "verified_by": {
     "type": "uuid",
     "notnull": false,
     "default": null
    },
    "created_by": {
     "type": "uuid",
     "notnull": false,
     "default": null
    },
    "created_at": {
     "type": "timestamp with time zone",
     "notnull": true,
     "default": {
      "kind": "now"
     }
    },
    "updated_at": {
     "type": "timestamp with time zone",
     "notnull": true,
     "default": {
      "kind": "now"
     }
    },
    "completed_at": {
     "type": "timestamp with time zone",
     "notnull": false,
     "default": null
    },
    "max_claimants": {
     "type": "integer",
     "notnull": false,
     "default": {
      "kind": "value",
      "value": 1
     }
    },
    "links": {
     "type": "jsonb",
     "notnull": true,
     "default": {
      "kind": "value",
      "value": []
     }
    },
    "images": {
     "type": "jsonb",
     "notnull": true,
     "default": {
      "kind": "value",
      "value": []
     }
    },
    "due_date": {
     "type": "date",
     "notnull": false,
     "default": null
    }
   },
   "pk": [
    "id"
   ],
   "unique": [
    {
     "name": "tasks_pkey",
     "primary": true,
     "columns": [
      "id"
     ],
     "where": null
    }
   ],
   "fks": [
    {
     "name": "tasks_claimed_by_fkey",
     "columns": [
      "claimed_by"
     ],
     "table": "profiles",
     "refColumns": [
      "id"
     ],
     "onDelete": "no action"
    },
    {
     "name": "tasks_created_by_fkey",
     "columns": [
      "created_by"
     ],
     "table": "profiles",
     "refColumns": [
      "id"
     ],
     "onDelete": "no action"
    },
    {
     "name": "tasks_verified_by_fkey",
     "columns": [
      "verified_by"
     ],
     "table": "profiles",
     "refColumns": [
      "id"
     ],
     "onDelete": "no action"
    }
   ],
   "enums": {
    "status": {
     "constraint": "tasks_status_check",
     "values": [
      "open",
      "closed",
      "completed"
     ]
    },
    "subteam": {
     "constraint": "tasks_subteam_values_chk",
     "values": [
      "Mechanical",
      "Electrical",
      "Programming",
      "CAD",
      "Fabrication",
      "Media",
      "Business/Outreach",
      "Drive Team",
      "Robot Construction",
      "Field & Pit",
      "Strategy and Scouting",
      "Management"
     ]
    }
   }
  }
 },
 "functions": {
  "_apply_event_edit": [
   {
    "args": [
     "p_event",
     "p_event_time",
     "p_category",
     "p_actor",
     "p_reason"
    ],
    "required": 5
   }
  ],
  "admin_delete_member": [
   {
    "args": [
     "p_member"
    ],
    "required": 1
   }
  ],
  "admin_get_members": [
   {
    "args": [],
    "required": 0
   }
  ],
  "admin_revert_claim": [
   {
    "args": [
     "p_task",
     "p_member"
    ],
    "required": 2
   }
  ],
  "admin_set_member_role": [
   {
    "args": [
     "p_member",
     "p_role",
     "p_grant"
    ],
    "required": 3
   }
  ],
  "approve_access_request": [
   {
    "args": [
     "p_request",
     "p_role"
    ],
    "required": 2
   }
  ],
  "approve_cert_request": [
   {
    "args": [
     "p_request"
    ],
    "required": 1
   }
  ],
  "approve_parent_link": [
   {
    "args": [
     "p_request"
    ],
    "required": 1
   }
  ],
  "auto_close_open_checkins": [
   {
    "args": [],
    "required": 0
   }
  ],
  "claim_profile": [
   {
    "args": [],
    "required": 0
   }
  ],
  "claim_task": [
   {
    "args": [
     "p_task"
    ],
    "required": 1
   }
  ],
  "clear_hour_goal": [
   {
    "args": [
     "p_member",
     "p_season"
    ],
    "required": 2
   }
  ],
  "deny_access_request": [
   {
    "args": [
     "p_request"
    ],
    "required": 1
   }
  ],
  "deny_cert_request": [
   {
    "args": [
     "p_request"
    ],
    "required": 1
   }
  ],
  "deny_parent_link": [
   {
    "args": [
     "p_request"
    ],
    "required": 1
   }
  ],
  "get_calendar_token": [
   {
    "args": [],
    "required": 0
   }
  ],
  "has_role": [
   {
    "args": [
     "check_role"
    ],
    "required": 1
   }
  ],
  "invoke_cron_notify": [
   {
    "args": [
     "p_job"
    ],
    "required": 1
   }
  ],
  "invoke_discord_calendar": [
   {
    "args": [],
    "required": 0
   }
  ],
  "is_admin": [
   {
    "args": [],
    "required": 0
   }
  ],
  "is_staff": [
   {
    "args": [],
    "required": 0
   }
  ],
  "link_guardian": [
   {
    "args": [
     "p_parent",
     "p_student"
    ],
    "required": 2
   }
  ],
  "my_access_request_status": [
   {
    "args": [],
    "required": 0
   }
  ],
  "notify_schedule_change": [
   {
    "args": [
     "p_title",
     "p_body",
     "p_ref"
    ],
    "required": 3
   }
  ],
  "readiness_summary": [
   {
    "args": [],
    "required": 0
   }
  ],
  "release_task": [
   {
    "args": [
     "p_task"
    ],
    "required": 1
   }
  ],
  "request_cert": [
   {
    "args": [
     "p_skill",
     "p_note"
    ],
    "required": 1
   }
  ],
  "request_logged_hours_correction": [
   {
    "args": [
     "p_entry",
     "p_note",
     "p_proposed_type",
     "p_proposed_hours",
     "p_proposed_date"
    ],
    "required": 5
   }
  ],
  "request_parent_link": [
   {
    "args": [
     "p_student",
     "p_note"
    ],
    "required": 1
   }
  ],
  "request_session_correction": [
   {
    "args": [
     "p_checkin",
     "p_checkout",
     "p_note",
     "p_proposed_in",
     "p_proposed_out",
     "p_proposed_category"
    ],
    "required": 6
   }
  ],
  "resolve_logged_hours_correction": [
   {
    "args": [
     "p_id",
     "p_approve",
     "p_resolution",
     "p_apply_type",
     "p_apply_hours",
     "p_apply_date"
    ],
    "required": 6
   }
  ],
  "resolve_session_correction": [
   {
    "args": [
     "p_id",
     "p_approve",
     "p_resolution",
     "p_apply_in",
     "p_apply_out",
     "p_apply_category"
    ],
    "required": 6
   }
  ],
  "rotate_calendar_token": [
   {
    "args": [],
    "required": 0
   }
  ],
  "set_hour_goal": [
   {
    "args": [
     "p_member",
     "p_season",
     "p_target",
     "p_categories"
    ],
    "required": 4
   }
  ],
  "set_session_job": [
   {
    "args": [
     "p_task"
    ],
    "required": 1
   }
  ],
  "staff_add_event": [
   {
    "args": [
     "p_member",
     "p_type",
     "p_event_time",
     "p_category",
     "p_reason"
    ],
    "required": 5
   }
  ],
  "staff_add_hour_adjustment": [
   {
    "args": [
     "p_member",
     "p_category",
     "p_hours",
     "p_reason"
    ],
    "required": 4
   }
  ],
  "staff_add_manual_session": [
   {
    "args": [
     "p_member",
     "p_in",
     "p_out",
     "p_category",
     "p_reason"
    ],
    "required": 5
   }
  ],
  "staff_delete_logged_hours": [
   {
    "args": [
     "p_entry"
    ],
    "required": 1
   }
  ],
  "staff_edit_event": [
   {
    "args": [
     "p_event",
     "p_event_time",
     "p_category",
     "p_reason"
    ],
    "required": 4
   }
  ],
  "staff_edit_logged_hours": [
   {
    "args": [
     "p_entry",
     "p_type",
     "p_hours",
     "p_date"
    ],
    "required": 4
   }
  ],
  "staff_override_attendance": [
   {
    "args": [
     "target_member",
     "new_type"
    ],
    "required": 2
   }
  ],
  "staff_set_discord_confirmed": [
   {
    "args": [
     "p_application",
     "p_confirmed"
    ],
    "required": 2
   }
  ],
  "staff_set_event": [
   {
    "args": [
     "p_event",
     "p_type",
     "p_event_time",
     "p_category",
     "p_reason"
    ],
    "required": 5
   }
  ],
  "staff_void_event": [
   {
    "args": [
     "p_event",
     "p_reason"
    ],
    "required": 2
   }
  ],
  "study_current_streak": [
   {
    "args": [
     "p_member",
     "p_goal"
    ],
    "required": 2
   }
  ],
  "study_strip": [
   {
    "args": [
     "p_member",
     "p_goal"
    ],
    "required": 2
   }
  ],
  "study_summary": [
   {
    "args": [],
    "required": 0
   }
  ],
  "submit_task": [
   {
    "args": [
     "p_task"
    ],
    "required": 1
   }
  ],
  "unlink_guardian": [
   {
    "args": [
     "p_parent",
     "p_student"
    ],
    "required": 2
   }
  ],
  "verify_task": [
   {
    "args": [
     "p_task",
     "p_member",
     "p_approve"
    ],
    "required": 3
   }
  ]
 }
}
