// GENERATED by scripts/design-system/ds-sheet-previews.mjs — do not hand-edit.
// The composition is extracted from components/sheets/SheetsDemoCard.jsx, so the
// specimen card and this preview show the same markup by construction.
//
// The pattern is mounted UNARMED at its real 1920 x 1440 and the stage-shaped
// box around it is scaled down to fit the card. Nothing is re-laid-out for the
// cell. Ground and audience are set once on the deck root, never on the pattern.
//
// The box is NOT .frc-stage: that class carries the deck's one-sheet-at-a-time
// rule (.frc-stage .frc-sheet { display: none } unless [data-deck-active]), and
// an unarmed sheet inside one renders an empty card. It reproduces the stage's
// box instead — same position, size and clip — so the sheet lays out identically.
import { AgendaSheet, Step } from 'frc5669-design-system'
const S = 0.48

const Stage = ({ children }: any) => (
  <div className="frc-deck frc-ground-squadron frc-audience-internal" style={{ display: 'inline-grid' }}>
    <div style={{ width: Math.round(1920 * S), height: Math.round(1440 * S), overflow: 'hidden' }}>
      <div style={{ position: 'relative', width: 1920, height: 1440, overflow: 'hidden', transform: `scale(${S})`, transformOrigin: '0 0' }}>
        {children}
      </div>
    </div>
  </div>
)
export const Pattern = () => (
  <Stage>
    <AgendaSheet label="Agenda" footer={{ deckName: 'Sheet pattern reference', parts: ['Brief', 'Build', 'Field', 'Season'], partIndex: 0, sheet: 2, total: 26 }}>
      <span slot="eyebrow">This session</span>
      <span slot="title">What we cover today</span>
      <Step state="done"><span slot="title">Where the season stands</span><span slot="text">Two minutes on the schedule, then straight to the work.</span></Step>
      <Step state="current"><span slot="title">Drivetrain handoff</span><span slot="text">Mechanical walks Programming through the gearbox change.</span></Step>
      <Step><span slot="title">Shop safety refresh</span><span slot="text">Mill and bandsaw. Everyone, not just the certified.</span></Step>
      <Step><span slot="title">Open build</span><span slot="text">Subteam leads have the job board.</span></Step>
    </AgendaSheet>
  </Stage>
)