// GENERATED by scripts/design-system/ds-sheet-previews.mjs — do not hand-edit.
// The composition is extracted from components/sheets/SheetsDemoCard.jsx, so the
// specimen card and this preview show the same markup by construction.
//
// The pattern is mounted UNARMED at its real 1920 x 1440 and the stage-shaped
// box around it is scaled down to fit the card. Nothing is re-laid-out for the
// cell. Ground and audience are set once on the deck root, never on the pattern.
//
// The box is NOT .frc-stage: that class carries the deck's one-sheet-at-a-time
// rule (.frc-stage .frc-sheet { display: none } unless [data-deck-active]), and
// an unarmed sheet inside one renders an empty card. It reproduces the stage's
// box instead — same position, size and clip — so the sheet lays out identically.
import { AwardPlate, AwardSheet, Readout, ResultBanner } from 'frc5669-design-system'
const S = 0.48

const Stage = ({ children }: any) => (
  <div className="frc-deck frc-ground-squadron frc-audience-internal" style={{ display: 'inline-grid' }}>
    <div style={{ width: Math.round(1920 * S), height: Math.round(1440 * S), overflow: 'hidden' }}>
      <div style={{ position: 'relative', width: 1920, height: 1440, overflow: 'hidden', transform: `scale(${S})`, transformOrigin: '0 0' }}>
        {children}
      </div>
    </div>
  </div>
)
export const Pattern = () => (
  <Stage>
    <AwardSheet label="Award" footer={{ deckName: 'Sheet pattern reference', parts: ['Brief', 'Build', 'Field', 'Season'], partIndex: 3, sheet: 24, total: 26 }}>
      <span slot="eyebrow">Los Angeles regional</span>
      <span slot="title">What we brought home</span>
      <AwardPlate slot="plate">
        <span slot="eyebrow">Los Angeles regional</span>
        <span slot="name">Industrial Design Award</span>
        <span slot="event">Presented by General Motors</span>
        <span slot="year">2026</span>
      </AwardPlate>
      <ResultBanner tone="win"><span slot="tag">Win</span><span slot="title">Quarterfinal 2</span><span slot="note">Red alliance</span><span slot="score">88 - 74</span></ResultBanner>
      <ResultBanner><span slot="tag">Rank</span><span slot="title">Seeded fourth of 42</span><span slot="note">Selected first round</span><span slot="score">2.41</span></ResultBanner>
      <div className="frc-readout-stack">
        <Readout tone="ok"><span slot="label">Inspection</span><span slot="value">Passed, first pass</span></Readout>
        <Readout><span slot="label">Matches played</span><span slot="value">12</span></Readout>
      </div>
    </AwardSheet>
  </Stage>
)