// GENERATED by scripts/design-system/ds-sheet-previews.mjs — do not hand-edit.
// The composition is extracted from components/sheets/SheetsDemoCard.jsx, so the
// specimen card and this preview show the same markup by construction.
//
// The pattern is mounted UNARMED at its real 1920 x 1440 and the stage-shaped
// box around it is scaled down to fit the card. Nothing is re-laid-out for the
// cell. Ground and audience are set once on the deck root, never on the pattern.
//
// The box is NOT .frc-stage: that class carries the deck's one-sheet-at-a-time
// rule (.frc-stage .frc-sheet { display: none } unless [data-deck-active]), and
// an unarmed sheet inside one renders an empty card. It reproduces the stage's
// box instead — same position, size and clip — so the sheet lays out identically.
import { Blocker, BlockerSheet, Callout } from 'frc5669-design-system'
const S = 0.48

const Stage = ({ children }: any) => (
  <div className="frc-deck frc-ground-squadron frc-audience-internal" style={{ display: 'inline-grid' }}>
    <div style={{ width: Math.round(1920 * S), height: Math.round(1440 * S), overflow: 'hidden' }}>
      <div style={{ position: 'relative', width: 1920, height: 1440, overflow: 'hidden', transform: `scale(${S})`, transformOrigin: '0 0' }}>
        {children}
      </div>
    </div>
  </div>
)
export const Pattern = () => (
  <Stage>
    <BlockerSheet label="Blockers" footer={{ deckName: 'Sheet pattern reference', parts: ['Brief', 'Build', 'Field', 'Season'], partIndex: 1, sheet: 16, total: 26 }}>
      <span slot="eyebrow">Standing blockers</span>
      <span slot="title">What is stopping work</span>
      <Blocker id="b1" severity="fault"><span slot="state">Blocked</span><span slot="title">Router table down, four parts queued</span><span slot="owner">Fabrication</span></Blocker>
      <Blocker id="b2" severity="warn"><span slot="state">At risk</span><span slot="title">Shooter rollers not shipped</span><span slot="owner">Mechanical</span></Blocker>
      <Blocker id="b3" severity="warn"><span slot="state">At risk</span><span slot="title">Field elements not built for driver practice</span><span slot="owner">Robot Construction</span></Blocker>
      <Blocker id="b4" severity="ok"><span slot="state">Cleared</span><span slot="title">Second battery charger installed</span><span slot="owner">Electrical</span></Blocker>
      <div slot="aside">
        <Callout tone="fault"><span slot="title">Decision needed today</span><p className="frc-callout-text">Cut the climber, or move driver practice a week. The room picks one.</p></Callout>
        <Callout tone="quiet"><span slot="title">Owner rule</span><p className="frc-callout-text">Every blocker has a name next to it before this sheet closes.</p></Callout>
      </div>
    </BlockerSheet>
  </Stage>
)