// GENERATED by scripts/design-system/ds-sheet-previews.mjs — do not hand-edit.
// The composition is extracted from components/sheets/SheetsDemoCard.jsx, so the
// specimen card and this preview show the same markup by construction.
//
// The pattern is mounted at its real 1920 x 1440 on a real .frc-stage and the
// STAGE is scaled down to fit the card. Nothing is re-laid-out for the cell.
// Ground and audience are set once on the deck root, never on the pattern.
import { BOMSheet, Callout, Cutout, PartCallout, SpecRow, SpecTable } from 'frc5669-design-system'
const S = 0.48

const Stage = ({ children }: any) => (
  <div className="frc-deck frc-ground-squadron frc-audience-internal" style={{ display: 'inline-grid' }}>
    <div style={{ width: Math.round(1920 * S), height: Math.round(1440 * S), overflow: 'hidden' }}>
      <div className="frc-stage" data-aspect="4:3" style={{ transform: `scale(${S})`, transformOrigin: '0 0' }}>
        {children}
      </div>
    </div>
  </div>
)
export const Pattern = () => (
  <Stage>
    <BOMSheet label="BOM" footer={{ deckName: 'Sheet pattern reference', parts: ['Brief', 'Build', 'Field', 'Season'], partIndex: 1, sheet: 23, total: 26 }}>
      <span slot="eyebrow">Drivetrain</span>
      <span slot="title">What it is made of</span>
      <PartCallout>
        <Cutout slot="media" ground="shelf" width={180} height={140} file="cots-gearbox.png" />
        <span slot="name">MAXPlanetary, 3 stage</span>
        <span slot="vendor">REV Robotics</span>
        <span slot="pn">REV-21-2100</span>
        <span slot="price">$74.00</span>
        <span slot="note">Two per side. Order the 12 tooth pinion separately.</span>
      </PartCallout>
      <PartCallout>
        <Cutout slot="media" ground="shelf" width={180} height={140} file="cots-wheel.png" />
        <span slot="name">Colson wheel, 4 in</span>
        <span slot="vendor">AndyMark</span>
        <span slot="pn">am-0952</span>
        <span slot="price">$14.50</span>
        <span slot="note">Eight per robot, plus two spares in the pit.</span>
      </PartCallout>
      <SpecTable slot="totals">
        <span slot="caption">Totals</span>
        <SpecRow><span slot="label">Subtotal</span><span slot="value">$412.00</span></SpecRow>
        <SpecRow><span slot="label">Shipping</span><span slot="value">$38.00</span></SpecRow>
        <SpecRow emphasis><span slot="label">Total</span><span slot="value">$450.00</span></SpecRow>
      </SpecTable>
      <div slot="aside">
        <Callout tone="warn"><span slot="title">Lead time</span><p className="frc-callout-text">Ten days on the gearboxes. Order before Friday or week five slips.</p></Callout>
      </div>
    </BOMSheet>
  </Stage>
)