// GENERATED by scripts/design-system/ds-sheet-previews.mjs — do not hand-edit.
// The composition is extracted from components/sheets/SheetsDemoCard.jsx, so the
// specimen card and this preview show the same markup by construction.
//
// The pattern is mounted at its real 1920 x 1440 on a real .frc-stage and the
// STAGE is scaled down to fit the card. Nothing is re-laid-out for the cell.
// Ground and audience are set once on the deck root, never on the pattern.
import { Button, ClosingSheet, Cutout, IconArrowRight, SponsorTier, SponsorWall } from 'frc5669-design-system'
const S = 0.48

const Stage = ({ children }: any) => (
  <div className="frc-deck frc-ground-squadron frc-audience-internal" style={{ display: 'inline-grid' }}>
    <div style={{ width: Math.round(1920 * S), height: Math.round(1440 * S), overflow: 'hidden' }}>
      <div className="frc-stage" data-aspect="4:3" style={{ transform: `scale(${S})`, transformOrigin: '0 0' }}>
        {children}
      </div>
    </div>
  </div>
)
export const Pattern = () => (
  <Stage>
    <ClosingSheet label="Closing" footer={{ deckName: 'Sheet pattern reference', parts: ['Brief', 'Build', 'Field', 'Season'], partIndex: 3, sheet: 7, total: 26 }}>
      <span slot="eyebrow">That is the brief</span>
      <span slot="title">Shop opens at 15:30.</span>
      <span slot="lede">Tag in at the door, tag out when you leave, and put the tool back where the shadow is.</span>
      <span slot="next">
        <Button variant="primary" iconEnd={<IconArrowRight />}>Job board</Button>
        <Button variant="ghost">Ask a mentor</Button>
      </span>
      <SponsorWall slot="sponsors">
        <SponsorTier>
          <span slot="name">Lead sponsors</span>
          <Cutout ground="none" width={220} height={90} file="sponsor-lead-1.png" />
          <Cutout ground="none" width={220} height={90} file="sponsor-lead-2.png" />
        </SponsorTier>
      </SponsorWall>
    </ClosingSheet>
  </Stage>
)