// GENERATED by scripts/design-system/ds-sheet-previews.mjs — do not hand-edit.
// The composition is extracted from components/sheets/SheetsDemoCard.jsx, so the
// specimen card and this preview show the same markup by construction.
//
// The pattern is mounted UNARMED at its real 1920 x 1440 and the stage-shaped
// box around it is scaled down to fit the card. Nothing is re-laid-out for the
// cell. Ground and audience are set once on the deck root, never on the pattern.
//
// The box is NOT .frc-stage: that class carries the deck's one-sheet-at-a-time
// rule (.frc-stage .frc-sheet { display: none } unless [data-deck-active]), and
// an unarmed sheet inside one renders an empty card. It reproduces the stage's
// box instead — same position, size and clip — so the sheet lays out identically.
import { Badge, CompareRow, CompareSplit, ComparisonSheet } from 'frc5669-design-system'
const S = 0.48

const Stage = ({ children }: any) => (
  <div className="frc-deck frc-ground-squadron frc-audience-internal" style={{ display: 'inline-grid' }}>
    <div style={{ width: Math.round(1920 * S), height: Math.round(1440 * S), overflow: 'hidden' }}>
      <div style={{ position: 'relative', width: 1920, height: 1440, overflow: 'hidden', transform: `scale(${S})`, transformOrigin: '0 0' }}>
        {children}
      </div>
    </div>
  </div>
)
export const Pattern = () => (
  <Stage>
    <ComparisonSheet label="Comparison" footer={{ deckName: 'Sheet pattern reference', parts: ['Brief', 'Build', 'Field', 'Season'], partIndex: 1, sheet: 11, total: 26 }}>
      <span slot="eyebrow">Intake geometry</span>
      <span slot="title">Over the bumper, or under</span>
      <CompareSplit>
        <span slot="label">Criterion</span>
        <span slot="option-a">Over the bumper</span>
        <span slot="option-b">Under the bumper</span>
        <CompareRow lead="a"><span slot="label">Cycle time</span><span slot="a">Faster from the source</span><span slot="b">One extra beat every cycle</span></CompareRow>
        <CompareRow lead="b"><span slot="label">Build hours</span><span slot="a">Two weeks of iteration</span><span slot="b">Fits the frame we have</span></CompareRow>
        <CompareRow lead="a"><span slot="label">Reliability</span><span slot="a">Fewer jam paths</span><span slot="b">Jams under the bumper</span></CompareRow>
      </CompareSplit>
      <span slot="verdict">
        <Badge tone="ok">Decision: over the bumper</Badge>
        <Badge tone="warn">Revisit if the frame changes</Badge>
      </span>
    </ComparisonSheet>
  </Stage>
)