// GENERATED by scripts/design-system/ds-sheet-previews.mjs — do not hand-edit.
// The composition is extracted from components/sheets/SheetsDemoCard.jsx, so the
// specimen card and this preview show the same markup by construction.
//
// The pattern is mounted at its real 1920 x 1440 on a real .frc-stage and the
// STAGE is scaled down to fit the card. Nothing is re-laid-out for the cell.
// Ground and audience are set once on the deck root, never on the pattern.
import { Badge, CoverSheet } from 'frc5669-design-system'
const S = 0.48

const Stage = ({ children }: any) => (
  <div className="frc-deck frc-ground-squadron frc-audience-internal" style={{ display: 'inline-grid' }}>
    <div style={{ width: Math.round(1920 * S), height: Math.round(1440 * S), overflow: 'hidden' }}>
      <div className="frc-stage" data-aspect="4:3" style={{ transform: `scale(${S})`, transformOrigin: '0 0' }}>
        {children}
      </div>
    </div>
  </div>
)
export const Pattern = () => (
  <Stage>
    <CoverSheet label="Cover" footer={{ deckName: 'Sheet pattern reference', parts: ['Brief', 'Build', 'Field', 'Season'], partIndex: 0, sheet: 1, total: 26 }}>
      <span slot="eyebrow">Kickoff briefing</span>
      <span slot="title">Build season starts Saturday</span>
      <span slot="subtitle">What we are building, who is on what, and the three dates that do not move.</span>
      <span slot="meta"><Badge tone="accent" solid>2026-27</Badge></span>
    </CoverSheet>
  </Stage>
)