// GENERATED by scripts/design-system/ds-sheet-previews.mjs — do not hand-edit.
// The composition is extracted from components/sheets/SheetsDemoCard.jsx, so the
// specimen card and this preview show the same markup by construction.
//
// The pattern is mounted UNARMED at its real 1920 x 1440 and the stage-shaped
// box around it is scaled down to fit the card. Nothing is re-laid-out for the
// cell. Ground and audience are set once on the deck root, never on the pattern.
//
// The box is NOT .frc-stage: that class carries the deck's one-sheet-at-a-time
// rule (.frc-stage .frc-sheet { display: none } unless [data-deck-active]), and
// an unarmed sheet inside one renders an empty card. It reproduces the stage's
// box instead — same position, size and clip — so the sheet lays out identically.
import { DataSheet, Readout, SpecRow, SpecTable, StatBlock } from 'frc5669-design-system'
const S = 0.48

const Stage = ({ children }: any) => (
  <div className="frc-deck frc-ground-squadron frc-audience-internal" style={{ display: 'inline-grid' }}>
    <div style={{ width: Math.round(1920 * S), height: Math.round(1440 * S), overflow: 'hidden' }}>
      <div style={{ position: 'relative', width: 1920, height: 1440, overflow: 'hidden', transform: `scale(${S})`, transformOrigin: '0 0' }}>
        {children}
      </div>
    </div>
  </div>
)
export const Pattern = () => (
  <Stage>
    <DataSheet label="Data" footer={{ deckName: 'Sheet pattern reference', parts: ['Brief', 'Build', 'Field', 'Season'], partIndex: 1, sheet: 12, total: 26 }}>
      <span slot="eyebrow">Season to date</span>
      <span slot="title">Hours in the shop</span>
      <StatBlock slot="stat" tone="hero"><span slot="value">412</span><span slot="unit">hrs</span><span slot="label">Shop hours</span></StatBlock>
      <StatBlock slot="stat" size="sm"><span slot="value">38</span><span slot="label">Members active</span></StatBlock>
      <StatBlock slot="stat" size="sm" tone="warn"><span slot="value">9</span><span slot="label">Below the goal</span></StatBlock>
      <SpecTable>
        <span slot="caption">By subteam</span>
        <SpecRow><span slot="label">Mechanical</span><span slot="value">104 h</span></SpecRow>
        <SpecRow><span slot="label">Programming</span><span slot="value">88 h</span></SpecRow>
        <SpecRow emphasis><span slot="label">Electrical</span><span slot="value">52 h</span></SpecRow>
        <SpecRow><span slot="label">Media</span><span slot="value">21 h</span></SpecRow>
      </SpecTable>
      <div slot="aside">
        <div className="frc-readout-stack">
          <Readout><span slot="label">Meetings held</span><span slot="value">24</span></Readout>
          <Readout tone="ok"><span slot="label">On goal</span><span slot="value">29 of 38</span></Readout>
          <Readout tone="warn"><span slot="label">Behind</span><span slot="value">9</span></Readout>
        </div>
      </div>
    </DataSheet>
  </Stage>
)