// GENERATED by scripts/design-system/ds-sheet-previews.mjs — do not hand-edit.
// The composition is extracted from components/sheets/SheetsDemoCard.jsx, so the
// specimen card and this preview show the same markup by construction.
//
// The pattern is mounted at its real 1920 x 1440 on a real .frc-stage and the
// STAGE is scaled down to fit the card. Nothing is re-laid-out for the cell.
// Ground and audience are set once on the deck root, never on the pattern.
import { Callout, FieldDiagram, FieldSheet, Readout } from 'frc5669-design-system'
/** Field zone geometry. Structure, not copy: nobody reads a point list aloud. */
const ZONES = [
  { id: 'red-source', alliance: 'red', points: '0,0 300,0 300,300 0,300', at: [9, 19] },
  { id: 'red-amp', alliance: 'red', points: '0,500 300,500 300,800 0,800', at: [9, 81] },
  { id: 'neutral', points: '620,0 980,0 980,800 620,800', at: [50, 50] },
  { id: 'blue-source', alliance: 'blue', points: '1300,0 1600,0 1600,300 1300,300', at: [91, 19] },
  { id: 'blue-amp', alliance: 'blue', points: '1300,500 1600,500 1600,800 1300,800', at: [91, 81] },
]

const S = 0.48

const Stage = ({ children }: any) => (
  <div className="frc-deck frc-ground-squadron frc-audience-internal" style={{ display: 'inline-grid' }}>
    <div style={{ width: Math.round(1920 * S), height: Math.round(1440 * S), overflow: 'hidden' }}>
      <div className="frc-stage" data-aspect="4:3" style={{ transform: `scale(${S})`, transformOrigin: '0 0' }}>
        {children}
      </div>
    </div>
  </div>
)
export const Pattern = () => (
  <Stage>
    <FieldSheet label="Field" footer={{ deckName: 'Sheet pattern reference', parts: ['Brief', 'Build', 'Field', 'Season'], partIndex: 2, sheet: 22, total: 26 }}>
      <span slot="eyebrow">Field</span>
      <span slot="title">Where our cycles live</span>
      <FieldDiagram zones={ZONES} viewBox="0 0 1600 800" grid={8}>
        <span slot="zone" data-zone="red-source">Red source</span>
        <span slot="zone" data-zone="red-amp">Red amp</span>
        <span slot="zone" data-zone="neutral">Neutral zone</span>
        <span slot="zone" data-zone="blue-source">Blue source</span>
        <span slot="zone" data-zone="blue-amp">Blue amp</span>
        <span slot="key" className="frc-fd-key frc-fd-key-red">Red side</span>
        <span slot="key" className="frc-fd-key frc-fd-key-blue">Blue side</span>
        <span slot="key" className="frc-fd-key">Neutral</span>
      </FieldDiagram>
      <div slot="aside">
        <div className="frc-readout-stack">
          <Readout><span slot="label">Cycle, source to amp</span><span slot="value">8.4 s</span></Readout>
          <Readout tone="warn"><span slot="label">Contested lane</span><span slot="value">Neutral</span></Readout>
          <Readout tone="ok"><span slot="label">Auto start</span><span slot="value">Amp side</span></Readout>
        </div>
        <Callout><span slot="title">Click a zone</span><p className="frc-callout-text">It raises the label already drawn there and dims the rest.</p></Callout>
      </div>
    </FieldSheet>
  </Stage>
)