// GENERATED by scripts/design-system/ds-sheet-previews.mjs — do not hand-edit.
// The composition is extracted from components/sheets/SheetsDemoCard.jsx, so the
// specimen card and this preview show the same markup by construction.
//
// The pattern is mounted at its real 1920 x 1440 on a real .frc-stage and the
// STAGE is scaled down to fit the card. Nothing is re-laid-out for the cell.
// Ground and audience are set once on the deck root, never on the pattern.
import { HubSheet, JumpCard } from 'frc5669-design-system'
const S = 0.48

const Stage = ({ children }: any) => (
  <div className="frc-deck frc-ground-squadron frc-audience-internal" style={{ display: 'inline-grid' }}>
    <div style={{ width: Math.round(1920 * S), height: Math.round(1440 * S), overflow: 'hidden' }}>
      <div className="frc-stage" data-aspect="4:3" style={{ transform: `scale(${S})`, transformOrigin: '0 0' }}>
        {children}
      </div>
    </div>
  </div>
)
export const Pattern = () => (
  <Stage>
    <HubSheet label="Hub" cols={4}>
      <span slot="eyebrow">Where to</span>
      <span slot="title">Pick a part</span>
      <JumpCard href="#brief" state="done"><span slot="title">Brief</span><span slot="note">Where the season stands</span></JumpCard>
      <JumpCard href="#build"><span slot="title">Build</span><span slot="note">Mechanisms and blockers</span></JumpCard>
      <JumpCard href="#field"><span slot="title">Field</span><span slot="note">Match review and scouting</span></JumpCard>
      <JumpCard href="#season"><span slot="title">Season</span><span slot="note">Awards, sponsors, next year</span></JumpCard>
    </HubSheet>
  </Stage>
)