// GENERATED by scripts/design-system/ds-sheet-previews.mjs — do not hand-edit.
// The composition is extracted from components/sheets/SheetsDemoCard.jsx, so the
// specimen card and this preview show the same markup by construction.
//
// The pattern is mounted UNARMED at its real 1920 x 1440 and the stage-shaped
// box around it is scaled down to fit the card. Nothing is re-laid-out for the
// cell. Ground and audience are set once on the deck root, never on the pattern.
//
// The box is NOT .frc-stage: that class carries the deck's one-sheet-at-a-time
// rule (.frc-stage .frc-sheet { display: none } unless [data-deck-active]), and
// an unarmed sheet inside one renders an empty card. It reproduces the stage's
// box instead — same position, size and clip — so the sheet lays out identically.
import { HubSheet, JumpCard } from 'frc5669-design-system'
const S = 0.48

const Stage = ({ children }: any) => (
  <div className="frc-deck frc-ground-squadron frc-audience-internal" style={{ display: 'inline-grid' }}>
    <div style={{ width: Math.round(1920 * S), height: Math.round(1440 * S), overflow: 'hidden' }}>
      <div style={{ position: 'relative', width: 1920, height: 1440, overflow: 'hidden', transform: `scale(${S})`, transformOrigin: '0 0' }}>
        {children}
      </div>
    </div>
  </div>
)
export const Pattern = () => (
  <Stage>
    <HubSheet label="Hub" cols={4}>
      <span slot="eyebrow">Where to</span>
      <span slot="title">Pick a part</span>
      <JumpCard href="#brief" state="done"><span slot="title">Brief</span><span slot="note">Where the season stands</span></JumpCard>
      <JumpCard href="#build"><span slot="title">Build</span><span slot="note">Mechanisms and blockers</span></JumpCard>
      <JumpCard href="#field"><span slot="title">Field</span><span slot="note">Match review and scouting</span></JumpCard>
      <JumpCard href="#season"><span slot="title">Season</span><span slot="note">Awards, sponsors, next year</span></JumpCard>
    </HubSheet>
  </Stage>
)