// GENERATED by scripts/design-system/ds-sheet-previews.mjs — do not hand-edit.
// The composition is extracted from components/sheets/SheetsDemoCard.jsx, so the
// specimen card and this preview show the same markup by construction.
//
// The pattern is mounted at its real 1920 x 1440 on a real .frc-stage and the
// STAGE is scaled down to fit the card. Nothing is re-laid-out for the cell.
// Ground and audience are set once on the deck root, never on the pattern.
import { AllianceSplit, Callout, MatchBreakdownSheet, MatchClock, SpecRow, SpecTable } from 'frc5669-design-system'
const S = 0.48

const Stage = ({ children }: any) => (
  <div className="frc-deck frc-ground-squadron frc-audience-internal" style={{ display: 'inline-grid' }}>
    <div style={{ width: Math.round(1920 * S), height: Math.round(1440 * S), overflow: 'hidden' }}>
      <div className="frc-stage" data-aspect="4:3" style={{ transform: `scale(${S})`, transformOrigin: '0 0' }}>
        {children}
      </div>
    </div>
  </div>
)
export const Pattern = () => (
  <Stage>
    <MatchBreakdownSheet label="Match breakdown" footer={{ deckName: 'Sheet pattern reference', parts: ['Brief', 'Build', 'Field', 'Season'], partIndex: 2, sheet: 20, total: 26 }}>
      <span slot="eyebrow">Qualification 42</span>
      <span slot="title">Where the match was won</span>
      <AllianceSplit slot="score" outcome="red">
        <span slot="red-tag">Red alliance</span>
        <span slot="red-score">88</span>
        <span slot="red-teams">5669 &middot; 1678 &middot; 4322</span>
        <span slot="vs">Qual 42</span>
        <span slot="blue-tag">Blue alliance</span>
        <span slot="blue-score">74</span>
        <span slot="blue-teams">254 &middot; 973 &middot; 1671</span>
      </AllianceSplit>
      <MatchClock slot="clock" phase="teleop" remaining={0}><span slot="note">Final</span></MatchClock>
      <SpecTable slot="red">
        <span slot="caption">Red breakdown</span>
        <SpecRow><span slot="label">Autonomous</span><span slot="value">26</span></SpecRow>
        <SpecRow emphasis><span slot="label">Teleop cycles</span><span slot="value">41</span></SpecRow>
        <SpecRow><span slot="label">Endgame</span><span slot="value">21</span></SpecRow>
      </SpecTable>
      <SpecTable slot="blue">
        <span slot="caption">Blue breakdown</span>
        <SpecRow><span slot="label">Autonomous</span><span slot="value">30</span></SpecRow>
        <SpecRow><span slot="label">Teleop cycles</span><span slot="value">33</span></SpecRow>
        <SpecRow><span slot="label">Endgame</span><span slot="value">11</span></SpecRow>
      </SpecTable>
      <Callout tone="ok"><span slot="title">What decided it</span><p className="frc-callout-text">Two extra cycles in the last forty seconds, and a deep climb both alliances tried for.</p></Callout>
    </MatchBreakdownSheet>
  </Stage>
)