// GENERATED by scripts/design-system/ds-sheet-previews.mjs — do not hand-edit.
// The composition is extracted from components/sheets/SheetsDemoCard.jsx, so the
// specimen card and this preview show the same markup by construction.
//
// The pattern is mounted UNARMED at its real 1920 x 1440 and the stage-shaped
// box around it is scaled down to fit the card. Nothing is re-laid-out for the
// cell. Ground and audience are set once on the deck root, never on the pattern.
//
// The box is NOT .frc-stage: that class carries the deck's one-sheet-at-a-time
// rule (.frc-stage .frc-sheet { display: none } unless [data-deck-active]), and
// an unarmed sheet inside one renders an empty card. It reproduces the stage's
// box instead — same position, size and clip — so the sheet lays out identically.
import { Callout, IconTriangleAlert, ProcedureSheet, Step } from 'frc5669-design-system'
const S = 0.48

const Stage = ({ children }: any) => (
  <div className="frc-deck frc-ground-squadron frc-audience-internal" style={{ display: 'inline-grid' }}>
    <div style={{ width: Math.round(1920 * S), height: Math.round(1440 * S), overflow: 'hidden' }}>
      <div style={{ position: 'relative', width: 1920, height: 1440, overflow: 'hidden', transform: `scale(${S})`, transformOrigin: '0 0' }}>
        {children}
      </div>
    </div>
  </div>
)
export const Pattern = () => (
  <Stage>
    <ProcedureSheet label="Procedure" footer={{ deckName: 'Sheet pattern reference', parts: ['Brief', 'Build', 'Field', 'Season'], partIndex: 1, sheet: 10, total: 26 }}>
      <span slot="eyebrow">Mill</span>
      <span slot="title">Squaring stock</span>
      <Step state="done"><span slot="title">Face one side</span><span slot="text">Light passes. Deburr before it goes back in the vise.</span></Step>
      <Step state="current"><span slot="title">Locate the datum</span><span slot="text">Edge find both walls, zero the readout, write the offsets on the traveller.</span></Step>
      <Step><span slot="title">Cut the pocket</span><span slot="text">Rough at depth minus 0.020, finish in one pass, then check with the caliper.</span></Step>
      <div slot="aside">
        <Callout tone="warn" icon={<IconTriangleAlert />}>
          <span slot="title">Before you start</span>
          <p className="frc-callout-text">Stock clamped, sleeves down, mentor in the shop. Every time.</p>
        </Callout>
      </div>
    </ProcedureSheet>
  </Stage>
)