// GENERATED by scripts/design-system/ds-sheet-previews.mjs — do not hand-edit.
// The composition is extracted from components/sheets/SheetsDemoCard.jsx, so the
// specimen card and this preview show the same markup by construction.
//
// The pattern is mounted at its real 1920 x 1440 on a real .frc-stage and the
// STAGE is scaled down to fit the card. Nothing is re-laid-out for the cell.
// Ground and audience are set once on the deck root, never on the pattern.
import { Cutout, RoleCard, RosterSheet, SubteamBadge } from 'frc5669-design-system'
const S = 0.48

const Stage = ({ children }: any) => (
  <div className="frc-deck frc-ground-squadron frc-audience-internal" style={{ display: 'inline-grid' }}>
    <div style={{ width: Math.round(1920 * S), height: Math.round(1440 * S), overflow: 'hidden' }}>
      <div className="frc-stage" data-aspect="4:3" style={{ transform: `scale(${S})`, transformOrigin: '0 0' }}>
        {children}
      </div>
    </div>
  </div>
)
export const Pattern = () => (
  <Stage>
    <RosterSheet label="Roster" cols={2} footer={{ deckName: 'Sheet pattern reference', parts: ['Brief', 'Build', 'Field', 'Season'], partIndex: 1, sheet: 19, total: 26 }}>
      <span slot="eyebrow">Drive team</span>
      <span slot="title">Who is on what</span>
      <RoleCard>
        <Cutout slot="portrait" ground="none" width={160} height={160} file="member-cutout.png" />
        <span slot="name">A. Rivera</span>
        <span slot="title">Drive coach, class of 2027</span>
        <SubteamBadge slot="subteam">Drive Team</SubteamBadge>
        <SubteamBadge slot="subteam">Mechanical</SubteamBadge>
        <li slot="cert" data-status="certified" data-safety>Mill</li>
        <li slot="cert" data-status="certified">Bandsaw</li>
        <li slot="cert" data-status="in_progress">Lathe</li>
      </RoleCard>
      <RoleCard>
        <Cutout slot="portrait" ground="none" width={160} height={160} file="member-cutout-2.png" />
        <span slot="name">J. Okafor</span>
        <span slot="title">Driver, class of 2028</span>
        <SubteamBadge slot="subteam">Drive Team</SubteamBadge>
        <SubteamBadge slot="subteam">Programming</SubteamBadge>
        <li slot="cert" data-status="certified">Pit safety</li>
        <li slot="cert" data-status="in_progress" data-safety>Mill</li>
      </RoleCard>
    </RosterSheet>
  </Stage>
)