// GENERATED by scripts/design-system/ds-sheet-previews.mjs — do not hand-edit.
// The composition is extracted from components/sheets/SheetsDemoCard.jsx, so the
// specimen card and this preview show the same markup by construction.
//
// The pattern is mounted UNARMED at its real 1920 x 1440 and the stage-shaped
// box around it is scaled down to fit the card. Nothing is re-laid-out for the
// cell. Ground and audience are set once on the deck root, never on the pattern.
//
// The box is NOT .frc-stage: that class carries the deck's one-sheet-at-a-time
// rule (.frc-stage .frc-sheet { display: none } unless [data-deck-active]), and
// an unarmed sheet inside one renders an empty card. It reproduces the stage's
// box instead — same position, size and clip — so the sheet lays out identically.
import { Callout, Chip, IconCheck, SafetyNote, SafetySheet, Step } from 'frc5669-design-system'
const S = 0.48

const Stage = ({ children }: any) => (
  <div className="frc-deck frc-ground-squadron frc-audience-internal" style={{ display: 'inline-grid' }}>
    <div style={{ width: Math.round(1920 * S), height: Math.round(1440 * S), overflow: 'hidden' }}>
      <div style={{ position: 'relative', width: 1920, height: 1440, overflow: 'hidden', transform: `scale(${S})`, transformOrigin: '0 0' }}>
        {children}
      </div>
    </div>
  </div>
)
export const Pattern = () => (
  <Stage>
    <SafetySheet label="Safety" footer={{ deckName: 'Sheet pattern reference', parts: ['Brief', 'Build', 'Field', 'Season'], partIndex: 1, sheet: 18, total: 26 }}>
      <span slot="eyebrow">Shop safety</span>
      <span slot="title">The mill</span>
      <SafetyNote slot="note">
        <p>The mill is a two-person tool. Nobody runs it alone, and nobody runs it without a mentor in the shop.</p>
        <li slot="rule">Eye protection from the door, not from the machine.</li>
        <li slot="rule">Long hair tied back, sleeves down, no gloves at the spindle.</li>
        <li slot="rule">Stock clamped before the spindle turns. Every time.</li>
        <Chip slot="ppe">Eye protection</Chip>
        <Chip slot="ppe">Closed shoes</Chip>
        <Chip slot="ppe">Hearing protection</Chip>
      </SafetyNote>
      <Step state="current"><span slot="title">Check the vise</span><span slot="text">Jaws clean, stock seated on parallels, handle snug.</span></Step>
      <Step><span slot="title">Check the tool</span><span slot="text">Collet tight, tool length recorded, spindle clear of the stock.</span></Step>
      <div slot="aside">
        <Callout tone="ok" icon={<IconCheck />}><span slot="title">Certified to run this</span><p className="frc-callout-text">Four students and two mentors. The list is on the roster sheet.</p></Callout>
      </div>
    </SafetySheet>
  </Stage>
)