// GENERATED by scripts/design-system/ds-sheet-previews.mjs — do not hand-edit.
// The composition is extracted from components/sheets/SheetsDemoCard.jsx, so the
// specimen card and this preview show the same markup by construction.
//
// The pattern is mounted at its real 1920 x 1440 on a real .frc-stage and the
// STAGE is scaled down to fit the card. Nothing is re-laid-out for the cell.
// Ground and audience are set once on the deck root, never on the pattern.
import { Badge, Chip, GanttBar, GanttChart, ScheduleSheet } from 'frc5669-design-system'
const S = 0.48

const Stage = ({ children }: any) => (
  <div className="frc-deck frc-ground-squadron frc-audience-internal" style={{ display: 'inline-grid' }}>
    <div style={{ width: Math.round(1920 * S), height: Math.round(1440 * S), overflow: 'hidden' }}>
      <div className="frc-stage" data-aspect="4:3" style={{ transform: `scale(${S})`, transformOrigin: '0 0' }}>
        {children}
      </div>
    </div>
  </div>
)
export const Pattern = () => (
  <Stage>
    <ScheduleSheet label="Schedule" footer={{ deckName: 'Sheet pattern reference', parts: ['Brief', 'Build', 'Field', 'Season'], partIndex: 1, sheet: 14, total: 26 }}>
      <span slot="eyebrow">Build calendar</span>
      <span slot="title">Who is where, when</span>
      <GanttChart cols={6} today={54}>
        <span slot="tick">Wk 1</span><span slot="tick">Wk 2</span><span slot="tick">Wk 3</span>
        <span slot="tick">Wk 4</span><span slot="tick">Wk 5</span><span slot="tick">Wk 6</span>
        <GanttBar start={0} span={34} state="done"><span slot="label">Drivetrain</span><span slot="bar">Cut, welded, belted</span></GanttBar>
        <GanttBar start={18} span={40}><span slot="label">Intake</span><span slot="bar">Rev two on the bench</span></GanttBar>
        <GanttBar start={44} span={30} state="risk"><span slot="label">Shooter</span><span slot="bar">Waiting on rollers</span></GanttBar>
        <GanttBar start={62} span={24} state="blocked"><span slot="label">Climber</span><span slot="bar">Blocked on geometry</span></GanttBar>
      </GanttChart>
      <Chip slot="key">Done</Chip>
      <Chip slot="key">At risk</Chip>
      <Chip slot="key">Blocked</Chip>
      <span slot="foot"><Badge tone="warn">Two lanes cross week four</Badge></span>
    </ScheduleSheet>
  </Stage>
)