// GENERATED by scripts/design-system/ds-sheet-previews.mjs — do not hand-edit.
// The composition is extracted from components/sheets/SheetsDemoCard.jsx, so the
// specimen card and this preview show the same markup by construction.
//
// The pattern is mounted at its real 1920 x 1440 on a real .frc-stage and the
// STAGE is scaled down to fit the card. Nothing is re-laid-out for the cell.
// Ground and audience are set once on the deck root, never on the pattern.
import { Callout, FocusRow, FocusTable, ScoutRow, ScoutTable, ScoutingSheet } from 'frc5669-design-system'
const S = 0.48

const Stage = ({ children }: any) => (
  <div className="frc-deck frc-ground-squadron frc-audience-internal" style={{ display: 'inline-grid' }}>
    <div style={{ width: Math.round(1920 * S), height: Math.round(1440 * S), overflow: 'hidden' }}>
      <div className="frc-stage" data-aspect="4:3" style={{ transform: `scale(${S})`, transformOrigin: '0 0' }}>
        {children}
      </div>
    </div>
  </div>
)
export const Pattern = () => (
  <Stage>
    <ScoutingSheet label="Scouting" footer={{ deckName: 'Sheet pattern reference', parts: ['Brief', 'Build', 'Field', 'Season'], partIndex: 2, sheet: 21, total: 26 }}>
      <span slot="eyebrow">Alliance selection</span>
      <span slot="title">Who we want</span>
      <ScoutTable>
        <span slot="col">Team</span><span slot="col">Auto</span><span slot="col">Cycles</span><span slot="col">Climb</span><span slot="col">Notes</span>
        <ScoutRow id="s1" alliance="red"><span slot="team">5669</span><span slot="cell">12</span><span slot="cell">7</span><span slot="cell">Deep</span><span slot="cell">Clean cycles, no fouls</span></ScoutRow>
        <ScoutRow id="s2" alliance="red"><span slot="team">1678</span><span slot="cell">15</span><span slot="cell">9</span><span slot="cell">Deep</span><span slot="cell">Fast from the source</span></ScoutRow>
        <ScoutRow id="s3" alliance="blue"><span slot="team">254</span><span slot="cell">14</span><span slot="cell">8</span><span slot="cell">Shallow</span><span slot="cell">Defended late</span></ScoutRow>
        <ScoutRow id="s4" alliance="blue"><span slot="team">973</span><span slot="cell">9</span><span slot="cell">6</span><span slot="cell">None</span><span slot="cell">Battery swap between matches</span></ScoutRow>
      </ScoutTable>
      <div slot="aside">
        <FocusTable defaultActive="p1">
          <span slot="caption">Pick order</span>
          <FocusRow id="p1"><span slot="rank">01</span><span slot="label">1678</span><span slot="value">2.41</span></FocusRow>
          <FocusRow id="p2"><span slot="rank">02</span><span slot="label">254</span><span slot="value">2.28</span></FocusRow>
          <FocusRow id="p3"><span slot="rank">03</span><span slot="label">973</span><span slot="value">2.19</span></FocusRow>
        </FocusTable>
        <Callout><span slot="title">Clicking a row dims the others</span><p className="frc-callout-text">It never hides one. The whole list is on the sheet in a PDF.</p></Callout>
      </div>
    </ScoutingSheet>
  </Stage>
)