// GENERATED by scripts/design-system/ds-sheet-previews.mjs — do not hand-edit.
// The composition is extracted from components/sheets/SheetsDemoCard.jsx, so the
// specimen card and this preview show the same markup by construction.
//
// The pattern is mounted at its real 1920 x 1440 on a real .frc-stage and the
// STAGE is scaled down to fit the card. Nothing is re-laid-out for the cell.
// Ground and audience are set once on the deck root, never on the pattern.
import { SeasonLockup, SeasonSheet, StatBlock } from 'frc5669-design-system'
const S = 0.48

const Stage = ({ children }: any) => (
  <div className="frc-deck frc-ground-squadron frc-audience-internal" style={{ display: 'inline-grid' }}>
    <div style={{ width: Math.round(1920 * S), height: Math.round(1440 * S), overflow: 'hidden' }}>
      <div className="frc-stage" data-aspect="4:3" style={{ transform: `scale(${S})`, transformOrigin: '0 0' }}>
        {children}
      </div>
    </div>
  </div>
)
export const Pattern = () => (
  <Stage>
    <SeasonSheet label="Season" footer={{ deckName: 'Sheet pattern reference', parts: ['Brief', 'Build', 'Field', 'Season'], partIndex: 3, sheet: 26, total: 26 }}>
      <span slot="eyebrow">The season</span>
      <span slot="title">2026-27</span>
      <SeasonLockup slot="lockup" years="2026-27">Biocore</SeasonLockup>
      <StatBlock slot="stat" tone="hero"><span slot="value">5669</span><span slot="label">Techmen, Don Bosco Technical Institute</span></StatBlock>
      <StatBlock slot="stat" size="sm"><span slot="value">38</span><span slot="label">Students on the roster</span></StatBlock>
      <StatBlock slot="stat" size="sm"><span slot="value">3</span><span slot="label">Events entered</span></StatBlock>
    </SeasonSheet>
  </Stage>
)