// GENERATED by scripts/design-system/ds-sheet-previews.mjs — do not hand-edit.
// The composition is extracted from components/sheets/SheetsDemoCard.jsx, so the
// specimen card and this preview show the same markup by construction.
//
// The pattern is mounted UNARMED at its real 1920 x 1440 and the stage-shaped
// box around it is scaled down to fit the card. Nothing is re-laid-out for the
// cell. Ground and audience are set once on the deck root, never on the pattern.
//
// The box is NOT .frc-stage: that class carries the deck's one-sheet-at-a-time
// rule (.frc-stage .frc-sheet { display: none } unless [data-deck-active]), and
// an unarmed sheet inside one renders an empty card. It reproduces the stage's
// box instead — same position, size and clip — so the sheet lays out identically.
import { Chip, ImageFrame, SplitSheet } from 'frc5669-design-system'
const S = 0.48

const Stage = ({ children }: any) => (
  <div className="frc-deck frc-ground-squadron frc-audience-internal" style={{ display: 'inline-grid' }}>
    <div style={{ width: Math.round(1920 * S), height: Math.round(1440 * S), overflow: 'hidden' }}>
      <div style={{ position: 'relative', width: 1920, height: 1440, overflow: 'hidden', transform: `scale(${S})`, transformOrigin: '0 0' }}>
        {children}
      </div>
    </div>
  </div>
)
export const Pattern = () => (
  <Stage>
    <SplitSheet label="Split" media="right" footer={{ deckName: 'Sheet pattern reference', parts: ['Brief', 'Build', 'Field', 'Season'], partIndex: 1, sheet: 8, total: 26 }}>
      <span slot="eyebrow">Drivetrain</span>
      <span slot="title">Belted, not chained</span>
      <ImageFrame slot="media" kind="render" ratio="4 / 3" file="drivetrain-render.png">
        <span slot="caption">Rev 3, as released to the router</span>
      </ImageFrame>
      <p className="frc-body">Belts hold tension through an event without a mid-match check, and the gearbox drops in without a tensioner block.</p>
      <p className="frc-body-sm frc-dim">Trade: a belt skips a tooth under a hard hit. We accept that and carry two spares in the pit.</p>
      <div style={{ display: 'flex', gap: 16, flexWrap: 'wrap' }}>
        <Chip>6.75:1</Chip><Chip>16.4 ft/s</Chip><Chip selected>4 in colson</Chip>
      </div>
    </SplitSheet>
  </Stage>
)