// GENERATED by scripts/design-system/ds-sheet-previews.mjs — do not hand-edit.
// The composition is extracted from components/sheets/SheetsDemoCard.jsx, so the
// specimen card and this preview show the same markup by construction.
//
// The pattern is mounted at its real 1920 x 1440 on a real .frc-stage and the
// STAGE is scaled down to fit the card. Nothing is re-laid-out for the cell.
// Ground and audience are set once on the deck root, never on the pattern.
import { SubteamStatus, SubteamStatusSheet } from 'frc5669-design-system'
const S = 0.48

const Stage = ({ children }: any) => (
  <div className="frc-deck frc-ground-squadron frc-audience-internal" style={{ display: 'inline-grid' }}>
    <div style={{ width: Math.round(1920 * S), height: Math.round(1440 * S), overflow: 'hidden' }}>
      <div className="frc-stage" data-aspect="4:3" style={{ transform: `scale(${S})`, transformOrigin: '0 0' }}>
        {children}
      </div>
    </div>
  </div>
)
export const Pattern = () => (
  <Stage>
    <SubteamStatusSheet label="Subteam status" cols={3} footer={{ deckName: 'Sheet pattern reference', parts: ['Brief', 'Build', 'Field', 'Season'], partIndex: 1, sheet: 15, total: 26 }}>
      <span slot="eyebrow">Monday muster</span>
      <span slot="title">Where every subteam stands</span>
      <SubteamStatus tone="ok" progress={92}>
        <span slot="subteam">Mechanical</span><span slot="status">On plan</span>
        <span slot="label" >Drivetrain</span>
        <span slot="note">Drivetrain closed out. Starting the superstructure fixture.</span>
      </SubteamStatus>
      <SubteamStatus tone="warn" progress={54}>
        <span slot="subteam">Electrical</span><span slot="status">Behind</span>
        <span slot="note">Waiting on the second CAN run. Two members certified this week.</span>
      </SubteamStatus>
      <SubteamStatus tone="ok" progress={78}>
        <span slot="subteam">Programming</span><span slot="status">On plan</span>
        <span slot="note">Auto paths sim-tested. Needs the real drivetrain Thursday.</span>
      </SubteamStatus>
      <SubteamStatus tone="fault" progress={22}>
        <span slot="subteam">Fabrication</span><span slot="status">Blocked</span>
        <span slot="note">Router table down. Parts queued at the shop next door.</span>
      </SubteamStatus>
      <SubteamStatus tone="ok" progress={66}>
        <span slot="subteam">Media</span><span slot="status">On plan</span>
        <span slot="note">Build photos every meeting. Sponsor packet drafted.</span>
      </SubteamStatus>
      <SubteamStatus tone="default" progress={40}>
        <span slot="subteam">Business/Outreach</span><span slot="status">Steady</span>
        <span slot="note">Two sponsor calls booked. Chairmans essay in review.</span>
      </SubteamStatus>
    </SubteamStatusSheet>
  </Stage>
)