// GENERATED by scripts/design-system/ds-sheet-previews.mjs — do not hand-edit.
// The composition is extracted from components/sheets/SheetsDemoCard.jsx, so the
// specimen card and this preview show the same markup by construction.
//
// The pattern is mounted UNARMED at its real 1920 x 1440 and the stage-shaped
// box around it is scaled down to fit the card. Nothing is re-laid-out for the
// cell. Ground and audience are set once on the deck root, never on the pattern.
//
// The box is NOT .frc-stage: that class carries the deck's one-sheet-at-a-time
// rule (.frc-stage .frc-sheet { display: none } unless [data-deck-active]), and
// an unarmed sheet inside one renders an empty card. It reproduces the stage's
// box instead — same position, size and clip — so the sheet lays out identically.
import { Bar, BuildCountdown, TargetsSheet } from 'frc5669-design-system'
const S = 0.48

const Stage = ({ children }: any) => (
  <div className="frc-deck frc-ground-squadron frc-audience-internal" style={{ display: 'inline-grid' }}>
    <div style={{ width: Math.round(1920 * S), height: Math.round(1440 * S), overflow: 'hidden' }}>
      <div style={{ position: 'relative', width: 1920, height: 1440, overflow: 'hidden', transform: `scale(${S})`, transformOrigin: '0 0' }}>
        {children}
      </div>
    </div>
  </div>
)
export const Pattern = () => (
  <Stage>
    <TargetsSheet label="Targets" max={120} target={90} footer={{ deckName: 'Sheet pattern reference', parts: ['Brief', 'Build', 'Field', 'Season'], partIndex: 1, sheet: 17, total: 26 }}>
      <span slot="eyebrow">Season targets</span>
      <span slot="title">What we said we would hit</span>
      <Bar value={104}><span slot="label">Shop hours</span><span slot="value">104 of 90</span></Bar>
      <Bar value={88} tone="ok"><span slot="label">Members certified</span><span slot="value">88%</span></Bar>
      <Bar value={52} tone="warn"><span slot="label">Outreach hours</span><span slot="value">52 of 90</span></Bar>
      <Bar value={21} tone="fault"><span slot="label">Driver practice</span><span slot="value">21 of 90</span></Bar>
      <div slot="aside">
        <BuildCountdown value={31}><span slot="label">To bag and tag</span></BuildCountdown>
        <BuildCountdown value={9}><span slot="label">To the Ventura regional</span></BuildCountdown>
      </div>
    </TargetsSheet>
  </Stage>
)