// GENERATED by scripts/design-system/ds-sheet-previews.mjs — do not hand-edit.
// The composition is extracted from components/sheets/SheetsDemoCard.jsx, so the
// specimen card and this preview show the same markup by construction.
//
// The pattern is mounted at its real 1920 x 1440 on a real .frc-stage and the
// STAGE is scaled down to fit the card. Nothing is re-laid-out for the cell.
// Ground and audience are set once on the deck root, never on the pattern.
import { Callout, TimelineItem, TimelineSheet } from 'frc5669-design-system'
const S = 0.48

const Stage = ({ children }: any) => (
  <div className="frc-deck frc-ground-squadron frc-audience-internal" style={{ display: 'inline-grid' }}>
    <div style={{ width: Math.round(1920 * S), height: Math.round(1440 * S), overflow: 'hidden' }}>
      <div className="frc-stage" data-aspect="4:3" style={{ transform: `scale(${S})`, transformOrigin: '0 0' }}>
        {children}
      </div>
    </div>
  </div>
)
export const Pattern = () => (
  <Stage>
    <TimelineSheet label="Timeline" footer={{ deckName: 'Sheet pattern reference', parts: ['Brief', 'Build', 'Field', 'Season'], partIndex: 1, sheet: 13, total: 26 }}>
      <span slot="eyebrow">Build season</span>
      <span slot="title">Six weeks, four gates</span>
      <TimelineItem state="done"><span slot="when">Week one</span><span slot="title">Kickoff read</span><span slot="body">Manual read together, strategy poster on the wall.</span></TimelineItem>
      <TimelineItem state="done"><span slot="when">Week two</span><span slot="title">Prototype gate</span><span slot="body">Three intakes on the bench, one carried forward.</span></TimelineItem>
      <TimelineItem state="current"><span slot="when">Week four</span><span slot="title">Assembly</span><span slot="body">Drivetrain done, superstructure on the fixture.</span></TimelineItem>
      <TimelineItem state="risk"><span slot="when">Week six</span><span slot="title">Practice</span><span slot="body">Driver practice needs the field elements finished.</span></TimelineItem>
      <div slot="aside">
        <Callout><span slot="title">The gate that matters</span><p className="frc-callout-text">Week two. Everything after it assumes one intake, not three.</p></Callout>
      </div>
    </TimelineSheet>
  </Stage>
)